/*
 * Copyright (C) 2010-2012 Project SkyFire <http://www.projectskyfire.org/>
 * Copyright (C) 2008-2012 TrinityCore <http://www.trinitycore.org/>
 * Copyright (C) 2005-2012 MaNGOS <http://getmangos.com/>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/// \addtogroup u2w
/// @{
/// \file

// Note: this include need for be sure have full definition of class WorldSession
//       if this class definition not complete then VS for x64 release use different size for
//       struct OpcodeHandler in this header and Opcode.cpp and get totally wrong data from
//       table opcodeTable in source when Opcode.h included but WorldSession.h not included
#ifndef _OPCODES_H
#define _OPCODES_H

#include "Common.h"

/// List of Opcodes
enum Opcodes
{
    NUM_OPCODE_HANDLERS                              = (0xFFFF+1),
    UNKNOWN_OPCODE                                   = NUM_OPCODE_HANDLERS,
    NULL_OPCODE                                      = 0,

    CMSG_WORLD_TELEPORT                              = 0x05051,
    CMSG_TELEPORT_TO_UNIT                            = 0x00,
    SMSG_CHECK_FOR_BOTS                              = 0x00,
    CMSG_BOT_DETECTED2                               = 0x00,
    SMSG_FORCEACTIONSHOW                             = 0x00, /* old 0x05884 */
    SMSG_PETGODMODE                                  = 0x00, /* old 0x05606 */
    SMSG_GODMODE                                     = 0x00, /* old 0x02AA0 */
    SMSG_DESTRUCTIBLE_BUILDING_DAMAGE                = 0x00, /* old 0x00E24 */
    CMSG_CHAR_CREATE                                 = 0x045FF,
    CMSG_CHAR_ENUM                                   = 0x04051, // 4.3.2 15211
    CMSG_CHAR_DELETE                                 = 0x005F5,
    SMSG_CHAR_CREATE                                 = 0x04DCF,
    SMSG_CHAR_ENUM                                   = 0x00CF5, // 4.3.2 15211
    SMSG_CHAR_DELETE                                 = 0x0058D,
    CMSG_WORLD_LOGIN                                 = 0x00,
    CMSG_PLAYER_LOGIN                                = 0x00848, /* old 0x00326 */
    CMSG_LOAD_SCREEN_NOTIFY                          = 0x05800, /* old 0x00976 */
    SMSG_NEW_WORLD                                   = 0x00C21,
    SMSG_TRANSFER_PENDING                            = 0x01EB5,
    SMSG_TRANSFER_ABORTED                            = 0x00, /* old 0x00AA6 */
    SMSG_CHARACTER_LOGIN_FAILED                      = 0x00, /* old 0x04E00 */
    SMSG_LOGIN_SETTIMESPEED                          = 0x00, /* old 0x02002 */
    SMSG_GAMETIME_UPDATE                             = 0x00, /* old 0x01800 */
    CMSG_GAMETIME_SET                                = 0x00, /* old 0x03202 */
    SMSG_GAMETIME_SET                                = 0x00, /* old 0x06E26 */
    CMSG_GAMESPEED_SET                               = 0x00,
    SMSG_GAMESPEED_SET                               = 0x00, /* old 0x03A24 */
    CMSG_SERVERTIME                                  = 0x00,
    SMSG_SERVERTIME                                  = 0x00, /* old 0x02680 */
    CMSG_PLAYER_LOGOUT                               = 0x00, /* old 0x04826 */
    CMSG_LOGOUT_REQUEST                              = 0x00, /* old 0x04826 */
    SMSG_LOGOUT_RESPONSE                             = 0x00, /* old 0x04E00 */
    SMSG_LOGOUT_COMPLETE                             = 0x00, /* old 0x02406 */
    CMSG_LOGOUT_CANCEL                               = 0x00, /* old 0x07C20 */
    SMSG_LOGOUT_CANCEL_ACK                           = 0x00, /* old 0x03C22 */
    CMSG_NAME_QUERY                                  = 0x02DA3, /* old 0x07220 */
    SMSG_NAME_QUERY_RESPONSE                         = 0x0455D, /* old 0x05E20 */
    CMSG_PET_NAME_QUERY                              = 0x06DE5,
    SMSG_PET_NAME_QUERY_RESPONSE                     = 0x00, /* old 0x01004 */
    CMSG_GUILD_QUERY                                 = 0x00D4F, /* old 0x05C04 */
    SMSG_GUILD_QUERY_RESPONSE                        = 0x02D33, /* old 0x01AA4 */
    CMSG_COMMENTATOR_START_WARGAME                   = 0x00, /* old 0x04316 */
    SMSG_DB_REPLY                                    = 0x006D1,
    SMSG_HOTFIX_NOTIFY_BLOP                          = 0x004D5, /* old 0x0261E - sent after SMSG_AUTH_RESPONSE */
    SMSG_HOTFIX_NOTIFY                               = 0x00, // can be sent while ingame
    CMSG_REQUEST_HOTFIX                              = 0x00, // the client sends this after we send SMSG_HOTFIX_NOTIFY[_BLOP], only sent for the items that the player has in his inventory, that are flagged to be hotfixed
    CMSG_PAGE_TEXT_QUERY                             = 0x00, /* old 0x07E84 */
    SMSG_PAGE_TEXT_QUERY_RESPONSE                    = 0x00D09,
    CMSG_QUEST_QUERY                                 = 0x04535, /* old 0x00C26 */
    SMSG_QUEST_QUERY_RESPONSE                        = 0x00, /* old 0x03880 */
    CMSG_GAMEOBJECT_QUERY                            = 0x04523, // 4.3.2 15211
    SMSG_GAMEOBJECT_QUERY_RESPONSE                   = 0x0253D, // 4.3.2 15211
    CMSG_CREATURE_QUERY                              = 0x02591, // 4.3.2 15211
    SMSG_CREATURE_QUERY_RESPONSE                     = 0x025FB, // 4.3.2 15211
    CMSG_WHO                                         = 0x00, /* old 0x03226 */
    SMSG_WHO                                         = 0x00, /* old 0x06006 */
    CMSG_WHOIS                                       = 0x00, /* old 0x04480 */
    SMSG_WHOIS                                       = 0x00, /* old 0x02602 */
    CMSG_CONTACT_LIST                                = 0x00, /* old 0x044A2 */
    SMSG_CONTACT_LIST                                = 0x00DAF, /* old 0x04626 */
    SMSG_FRIEND_STATUS                               = 0x00, /* old 0x04E24 */
    CMSG_ADD_FRIEND                                  = 0x00, /* old 0x072A6 */
    CMSG_DEL_FRIEND                                  = 0x00, /* old 0x06EA0 */
    CMSG_SET_CONTACT_NOTES                           = 0x00, /* old 0x02402 */
    CMSG_ADD_IGNORE                                  = 0x00, /* old 0x056A6 */
    CMSG_DEL_IGNORE                                  = 0x00, /* old 0x02CA6 */
    CMSG_GROUP_INVITE                                = 0x00019,
    SMSG_GROUP_INVITE                                = 0x00, /* old 0x02C8A */
    CMSG_GROUP_CANCEL                                = 0x00,
    SMSG_GROUP_CANCEL                                = 0x00, /* old 0x07C04 */
    CMSG_GROUP_ACCEPT                                = 0x00,
    CMSG_GROUP_DECLINE                               = 0x00, /* old 0x00916 */
    SMSG_GROUP_DECLINE                               = 0x00, /* old 0x04A04 */
    CMSG_GROUP_UNINVITE                              = 0x00, /* old 0x02E24 */
    CMSG_GROUP_UNINVITE_GUID                         = 0x00,
    SMSG_GROUP_UNINVITE                              = 0x00, /* old 0x06C80 */
    CMSG_GROUP_SET_LEADER                            = 0x00, /* old 0x01456 */
    SMSG_GROUP_SET_LEADER                            = 0x00, /* old 0x02C84 */
    CMSG_LOOT_METHOD                                 = 0x00, /* old 0x03686 */
    CMSG_GROUP_DISBAND                               = 0x00,
    SMSG_GROUP_DESTROYED                             = 0x00, /* old 0x06C04 */
    SMSG_GROUP_LIST                                  = 0x00, /* old 0x07600 */
    SMSG_PARTY_MEMBER_STATS                          = 0x00, /* old 0x03822 */
    SMSG_PARTY_COMMAND_RESULT                        = 0x00, /* old 0x06A20 */
    CMSG_GUILD_CREATE                                = 0x00,
    CMSG_GUILD_INVITE                                = 0x00, /* old 0x04936 */
    SMSG_GUILD_INVITE                                = 0x00, /* old 0x086A8 */
    CMSG_GUILD_ACCEPT                                = 0x00, /* old 0x04924 */
    CMSG_GUILD_DECLINE                               = 0x00, /* old 0x0084C */
    SMSG_GUILD_DECLINE                               = 0x00,
    CMSG_GUILD_INFO                                  = 0x00,
    SMSG_GUILD_INFO                                  = 0x00,
    CMSG_GUILD_ROSTER                                = 0x01581,
    CMSG_REQUEST_GUILD_ROSTER                        = 0x00,
    SMSG_GUILD_ROSTER                                = 0x00, /* old 0x00C1E */
    CMSG_GUILD_PROMOTE                               = 0x00,
    CMSG_GUILD_DEMOTE                                = 0x00,
    CMSG_GUILD_LEAVE                                 = 0x01505,
    CMSG_GUILD_REMOVE                                = 0x00, /* old 0x00248 */
    CMSG_GUILD_DISBAND                               = 0x00,
    CMSG_GUILD_LEADER                                = 0x00,
    CMSG_GUILD_MOTD                                  = 0x00, /* old 0x0000C */
    CMSG_QUERY_GUILD_REWARDS                         = 0x00, /* old 0x00088 - Possible */
    CMSG_QUERY_GUILD_MAX_XP                          = 0x00,
    CMSG_QUERY_GUILD_XP                              = 0x03D01,
    SMSG_GUILD_EVENT                                 = 0x00, /* old 0x05CA4 */
    SMSG_GUILD_UPDATE_ROSTER                         = 0x00,
    SMSG_GUILD_RANKS_UPDATE                          = 0x00,
    SMSG_GUILD_REWARDS_LIST                          = 0x00670,
    SMSG_GUILD_TRADESKILL_UPDATE                     = 0x00, /* old 0x0441E */
    SMSG_GUILD_MAX_DAILY_XP                          = 0x01684,
    SMSG_GUILD_NEWS_UPDATE                           = 0x00C61,
    CMSG_GUILD_REQUEST_NEWS                          = 0x5589,
    SMSG_GUILD_XP_UPDATE                             = 0x00,
    SMSG_GUILD_COMMAND_RESULT                        = 0x00,
    SMSG_GUILD_CRITERIA_DATA                         = 0x00,
    CMSG_MESSAGECHAT_SAY                             = 0x022E0, // 4.3.2 15211
    CMSG_MESSAGECHAT_YELL                            = 0x02260, // 4.3.2 15211
    CMSG_MESSAGECHAT_CHANNEL                         = 0x10005, /* old 0x0152C */
    CMSG_MESSAGECHAT_WHISPER                         = 0x02881, /* old 0x0030E */
    CMSG_MESSAGECHAT_GUILD                           = 0x10007, /* old 0x0110E */
    CMSG_MESSAGECHAT_OFFICER                         = 0x10008, /* old 0x0154E */
    CMSG_MESSAGECHAT_AFK                             = 0x10009, /* old 0x0134C */
    CMSG_MESSAGECHAT_DND                             = 0x1000A, /* old 0x0072C */
    CMSG_MESSAGECHAT_EMOTE                           = 0x1000B, /* old 0x04886 */
    CMSG_MESSAGECHAT_PARTY                           = 0x1000C, /* old 0x0130E */
    CMSG_MESSAGECHAT_PARTY_LEADER                    = 0x1000D,
    CMSG_MESSAGECHAT_RAID                            = 0x1000E, /* old 0x0154C */
    CMSG_MESSAGECHAT_RAID_LEADER                     = 0x10011,
    CMSG_MESSAGECHAT_BATTLEGROUND                    = 0x10012, /* old 0x0130C */
    CMSG_MESSAGECHAT_BATTLEGROUND_LEADER             = 0x10013,
    CMSG_MESSAGECHAT_RAID_WARNING                    = 0x10014, /* old 0x0136C */
    SMSG_MESSAGECHAT                                 = 0x00529, // 4.3.2 15211
    CMSG_JOIN_CHANNEL                                = 0x02241,
    CMSG_LEAVE_CHANNEL                               = 0x00, /* old 0x0070E */
    SMSG_CHANNEL_NOTIFY                              = 0x00, /* old 0x07A26 */
    CMSG_CHANNEL_LIST                                = 0x00, /* old 0x0132E */
    SMSG_CHANNEL_LIST                                = 0x00, /* old 0x03480 */
    CMSG_CHANNEL_PASSWORD                            = 0x00, /* old 0x0012E */
    CMSG_CHANNEL_SET_OWNER                           = 0x00, /* old 0x0114E */
    CMSG_CHANNEL_OWNER                               = 0x00, /* old 0x0034E */
    CMSG_CHANNEL_MODERATOR                           = 0x00, /* old 0x0172E */
    CMSG_CHANNEL_UNMODERATOR                         = 0x00, /* old 0x0116E */
    CMSG_CHANNEL_MUTE                                = 0x00, /* old 0x0050E */
    CMSG_CHANNEL_UNMUTE                              = 0x00, /* old 0x0054C */
    CMSG_CHANNEL_INVITE                              = 0x00, /* old 0x0012C */
    CMSG_CHANNEL_KICK                                = 0x00, /* old 0x0176C */
    CMSG_CHANNEL_ROSTER_INFO                         = 0x00,
    CMSG_CHANNEL_BAN                                 = 0x00, /* old 0x0054E */
    CMSG_CHANNEL_UNBAN                               = 0x00, /* old 0x0076E */
    CMSG_CHANNEL_ANNOUNCEMENTS                       = 0x00, /* old 0x0056E */
    CMSG_CHANNEL_MODERATE                            = 0x00, /* old 0x0074E */
    SMSG_UPDATE_OBJECT                               = 0x00, /* old 0x04606 */
    SMSG_DESTROY_OBJECT                              = 0x04DAF,
    CMSG_USE_ITEM                                    = 0x00, /* old 0x05A84 */
    CMSG_OPEN_ITEM                                   = 0x00, /* old 0x01824 */
    CMSG_READ_ITEM                                   = 0x00, /* old 0x04004 */
    SMSG_READ_ITEM_OK                                = 0x00, /* old 0x056A2 */
    SMSG_READ_ITEM_FAILED                            = 0x00, /* old 0x01626 */
    SMSG_ITEM_COOLDOWN                               = 0x00, /* old 0x02C06 */
    CMSG_GAMEOBJ_USE                                 = 0x00, /* old 0x06806 */
    CMSG_DESTROY_ITEMS                               = 0x00, /* old 0x076A6 */
    SMSG_GAMEOBJECT_CUSTOM_ANIM                      = 0x00, /* old 0x00626 */
    CMSG_AREATRIGGER                                 = 0x00, /* old 0x05E84 */
    MSG_MOVE_START_FORWARD                           = 0x02905,
    MSG_MOVE_START_BACKWARD                          = 0x00361, /* old 0x02623 */
    MSG_MOVE_STOP                                    = 0x00325,
    MSG_MOVE_START_STRAFE_LEFT                       = 0x023E4,
    MSG_MOVE_START_STRAFE_RIGHT                      = 0x00, /* old 0x02221 */
    MSG_MOVE_STOP_STRAFE                             = 0x00, /* old 0x076A3 */
    MSG_MOVE_JUMP                                    = 0x00904,
    MSG_MOVE_START_TURN_LEFT                         = 0x001C1,
    MSG_MOVE_START_TURN_RIGHT                        = 0x00161,
    MSG_MOVE_STOP_TURN                               = 0x02161,
    MSG_MOVE_START_PITCH_UP                          = 0x00, /* old 0x036B1 */
    MSG_MOVE_START_PITCH_DOWN                        = 0x00, /* old 0x06491 */
    MSG_MOVE_STOP_PITCH                              = 0x00, /* old 0x07033 */
    MSG_MOVE_SET_RUN_MODE                            = 0x00, /* old 0x072B1 */
    MSG_MOVE_SET_WALK_MODE                           = 0x00, /* old 0x03211 */
    MSG_MOVE_TOGGLE_LOGGING                          = 0x00,
    MSG_MOVE_TELEPORT                                = 0x014D5,
    MSG_MOVE_TELEPORT_CHEAT                          = 0x00, /* old 0x074B3 */
    MSG_MOVE_TELEPORT_ACK                            = 0x00981,
    MSG_MOVE_TOGGLE_FALL_LOGGING                     = 0x00,
    MSG_MOVE_FALL_LAND                               = 0x00381,
    MSG_MOVE_START_SWIM                              = 0x00, /* old 0x02291 */
    MSG_MOVE_STOP_SWIM                               = 0x00, /* old 0x022B1 */
    MSG_MOVE_SET_RUN_SPEED_CHEAT                     = 0x00,
    MSG_MOVE_SET_RUN_SPEED                           = 0x01CB0,
    MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT                = 0x00,
    MSG_MOVE_SET_RUN_BACK_SPEED                      = 0x00E04,
    MSG_MOVE_SET_WALK_SPEED_CHEAT                    = 0x00,
    MSG_MOVE_SET_WALK_SPEED                          = 0x01E90,
    MSG_MOVE_SET_SWIM_SPEED_CHEAT                    = 0x00,
    MSG_MOVE_SET_SWIM_SPEED                          = 0x00C75,
    MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT               = 0x00,
    MSG_MOVE_SET_SWIM_BACK_SPEED                     = 0x00, /* old 0x00E1C */
    MSG_MOVE_SET_ALL_SPEED_CHEAT                     = 0x00,
    MSG_MOVE_SET_TURN_RATE_CHEAT                     = 0x00,
    MSG_MOVE_SET_TURN_RATE                           = 0x00, /* old 0x06608 */
    MSG_MOVE_TOGGLE_COLLISION_CHEAT                  = 0x00, /* old 0x07011 */
    MSG_MOVE_SET_FACING                              = 0x02325,
    MSG_MOVE_SET_PITCH                               = 0x00, /* old 0x064A1 */
    MSG_MOVE_WORLDPORT_ACK                           = 0x00, /* old 0x04334 */
    SMSG_MONSTER_MOVE                                = 0x00, /* old 0x060A0 */
    SMSG_MOVE_WATER_WALK                             = 0x00,
    SMSG_MOVE_LAND_WALK                              = 0x00,
    MSG_MOVE_SET_RAW_POSITION_ACK                    = 0x00,
    CMSG_MOVE_SET_RAW_POSITION                       = 0x00,
    SMSG_FORCE_RUN_SPEED_CHANGE                      = 0x00, /* old 0x046A8 */
    CMSG_FORCE_RUN_SPEED_CHANGE_ACK                  = 0x00, /* old 0x060A1 */
    SMSG_FORCE_RUN_BACK_SPEED_CHANGE                 = 0x00, /* old 0x02EBC */
    CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK             = 0x00,
    SMSG_FORCE_SWIM_SPEED_CHANGE                     = 0x00,
    CMSG_FORCE_SWIM_SPEED_CHANGE_ACK                 = 0x00,
    SMSG_FORCE_MOVE_ROOT                             = 0x00, /* old 0x0461E */
    CMSG_FORCE_MOVE_ROOT_ACK                         = 0x02344,
    SMSG_FORCE_MOVE_UNROOT                           = 0x00, /* old 0x00408 */
    CMSG_FORCE_MOVE_UNROOT_ACK                       = 0x00181,
    MSG_MOVE_ROOT                                    = 0x00,
    MSG_MOVE_UNROOT                                  = 0x00, /* old 0x00408 */
    MSG_MOVE_HEARTBEAT                               = 0x02B81,
    SMSG_MOVE_KNOCK_BACK                             = 0x00,
    CMSG_MOVE_KNOCK_BACK_ACK                         = 0x00, /* old 0x034A3 */
    MSG_MOVE_KNOCK_BACK                              = 0x00,
    SMSG_MOVE_FEATHER_FALL                           = 0x00,
    SMSG_MOVE_NORMAL_FALL                            = 0x00,
    SMSG_MOVE_SET_HOVER                              = 0x00,
    SMSG_MOVE_UNSET_HOVER                            = 0x00,
    SMSG_MOVE_SET_WALK_IN_AIR                        = 0x00,
    SMSG_MOVE_UNSET_WALK_IN_AIR                      = 0x00,
    CMSG_MOVE_HOVER_ACK                              = 0x00, /* old 0x066A3 */
    MSG_MOVE_HOVER                                   = 0x00,
    CMSG_TRIGGER_CINEMATIC_CHEAT                     = 0x00,
    CMSG_OPENING_CINEMATIC                           = 0x00, /* old 0x03800 */
    SMSG_TRIGGER_CINEMATIC                           = 0x06D43, /* old 0x00E04 */
    CMSG_NEXT_CINEMATIC_CAMERA                       = 0x00, /* old 0x01684 */
    CMSG_COMPLETE_CINEMATIC                          = 0x00, /* old 0x06682 */
    SMSG_TUTORIAL_FLAGS                              = 0x04D8F, // 4.3.2 15211
    CMSG_TUTORIAL_FLAG                               = 0x00, /* old 0x03E84 */
    CMSG_TUTORIAL_CLEAR                              = 0x00, /* old 0x01AA6 */
    CMSG_TUTORIAL_RESET                              = 0x00, /* old 0x07C82 */
    CMSG_STANDSTATECHANGE                            = 0x00, /* old 0x07804 */
    CMSG_EMOTE                                       = 0x00, /* old 0x05E86 */
    SMSG_EMOTE                                       = 0x065F9,
    CMSG_TEXT_EMOTE                                  = 0x00, /* old 0x04886 */
    SMSG_TEXT_EMOTE                                  = 0x045BD,
    CMSG_AUTOEQUIP_GROUND_ITEM                       = 0x00,
    CMSG_AUTOSTORE_GROUND_ITEM                       = 0x00,
    CMSG_AUTOSTORE_LOOT_ITEM                         = 0x00, /* old 0x00424 */
    CMSG_STORE_LOOT_IN_SLOT                          = 0x00,
    CMSG_AUTOSTORE_LOOT_CURRENCY                     = 0x00,
    CMSG_AUTOEQUIP_ITEM                              = 0x00, /* old 0x03A80 */
    CMSG_AUTOSTORE_BAG_ITEM                          = 0x00, /* old 0x03680 */
    CMSG_SWAP_ITEM                                   = 0x00, /* old 0x06404 */
    CMSG_SWAP_INV_ITEM                               = 0x00,
    CMSG_SPLIT_ITEM                                  = 0x00, /* old 0x03206 */
    CMSG_AUTOEQUIP_ITEM_SLOT                         = 0x00, /* old 0x01E22 */
    OBSOLETE_DROP_ITEM                               = 0x00,
    CMSG_DESTROYITEM                                 = 0x00,
    SMSG_INVENTORY_CHANGE_FAILURE                    = 0x00, /* old 0x000A4 */
    SMSG_OPEN_CONTAINER                              = 0x00,
    CMSG_INSPECT                                     = 0x00, /* old 0x04222 */
    SMSG_INSPECT                                     = 0x00, /* old 0x03026 */
    CMSG_INITIATE_TRADE                              = 0x00, /* old 0x074A1 */
    CMSG_BEGIN_TRADE                                 = 0x00, /* old 0x066A1 */
    CMSG_BUSY_TRADE                                  = 0x00, /* old 0x06413 */
    CMSG_IGNORE_TRADE                                = 0x00, /* old 0x064B3 */
    CMSG_ACCEPT_TRADE                                = 0x00, /* old 0x03091 */
    CMSG_UNACCEPT_TRADE                              = 0x00, /* old 0x060A3 */
    CMSG_CANCEL_TRADE                                = 0x021E5,
    CMSG_SET_TRADE_ITEM                              = 0x00, /* old 0x02433 */
    CMSG_CLEAR_TRADE_ITEM                            = 0x00, /* old 0x07431 */
    CMSG_SET_TRADE_GOLD                              = 0x00, /* old 0x062B1 */
    SMSG_TRADE_STATUS                                = 0x00, /* old 0x024AA */
    SMSG_TRADE_STATUS_EXTENDED                       = 0x00, /* old 0x0462A */
    SMSG_INITIALIZE_FACTIONS                         = 0x00573, /* old 0x04E26 */
    SMSG_SET_FACTION_VISIBLE                         = 0x00, /* old 0x06C02 */
    SMSG_SET_FACTION_STANDING                        = 0x00, /* old 0x00422 */
    CMSG_SET_FACTION_ATWAR                           = 0x00, /* old 0x04402 */
    CMSG_SET_FACTION_CHEAT                           = 0x00,
    SMSG_SET_PROFICIENCY                             = 0x045C7, /* old 0x00EA2 */
    CMSG_SET_ACTION_BUTTON                           = 0x01451, /* old 0x00806 */
    SMSG_ACTION_BUTTONS                              = 0x01451,
    SMSG_INITIAL_SPELLS                              = 0x065D3, /* old 0x008A6 */
    SMSG_LEARNED_SPELL                               = 0x00,
    SMSG_SUPERCEDED_SPELL                            = 0x00,
    CMSG_NEW_SPELL_SLOT                              = 0x00,
    CMSG_CAST_SPELL                                  = 0x00, /* old 0x00A84 */
    CMSG_CANCEL_CAST                                 = 0x00, /* old 0x06620 */
    SMSG_CAST_FAILED                                 = 0x00, /* old 0x00800 */
    SMSG_SPELL_START                                 = 0x00, /* old 0x02084 */
    SMSG_SPELL_GO                                    = 0x00, /* old 0x07686 */
    SMSG_SPELL_FAILURE                               = 0x00, /* old 0x01204 */
    SMSG_SPELL_COOLDOWN                              = 0x00, /* old 0x04820 */
    SMSG_COOLDOWN_EVENT                              = 0x00, /* old 0x03224 */
    CMSG_CANCEL_AURA                                 = 0x00,
    SMSG_EQUIPMENT_SET_SAVED                         = 0x00, /* old 0x03C84 */
    SMSG_PET_CAST_FAILED                             = 0x00, /* old 0x07A06 */
    MSG_CHANNEL_START                                = 0x00,
    MSG_CHANNEL_UPDATE                               = 0x00,
    CMSG_CANCEL_CHANNELLING                          = 0x00, /* old 0x06482 */
    SMSG_AI_REACTION                                 = 0x06D5B,
    CMSG_SET_SELECTION                               = 0x00, /* old 0x05486 */
    CMSG_EQUIPMENT_SET_DELETE                        = 0x00, /* old 0x06E84 */
    CMSG_INSTANCE_LOCK_WARNING_RESPONSE              = 0x00,
    CMSG_UNUSED2                                     = 0x00,
    CMSG_ATTACKSWING                                 = 0x00, /* old 0x01226 */
    CMSG_ATTACKSTOP                                  = 0x00, /* old 0x04EA4 */
    SMSG_ATTACKSTART                                 = 0x00, /* old 0x03024 */
    SMSG_ATTACKSTOP                                  = 0x00, /* old 0x06AA0 */
    SMSG_ATTACKSWING_NOTINRANGE                      = 0x00, /* old 0x01606 */
    SMSG_ATTACKSWING_BADFACING                       = 0x00, /* old 0x04E04 */
    SMSG_INSTANCE_LOCK_WARNING_QUERY                 = 0x00,
    SMSG_ATTACKSWING_DEADTARGET                      = 0x00, /* old 0x05020 */
    SMSG_ATTACKSWING_CANT_ATTACK                     = 0x00, /* old 0x06E04 */
    SMSG_ATTACKERSTATEUPDATE                         = 0x00, /* old 0x03A04 */
    SMSG_BATTLEFIELD_PORT_DENIED                     = 0x00, /* old 0x09768 */
    SMSG_DAMAGE_DONE_OBSOLETE                        = 0x00,
    SMSG_UNIT_SPELLCAST_START                        = 0x00, /* old 0x01026 */
    SMSG_CANCEL_COMBAT                               = 0x00, /* old 0x012A6 */
    SMSG_SPELLBREAKLOG                               = 0x00, /* old 0x01482 */
    SMSG_SPELLHEALLOG                                = 0x00D1D, /* old 0x00EA0 */
    SMSG_SPELLENERGIZELOG                            = 0x005EF,
    SMSG_BREAK_TARGET                                = 0x00, /* old 0x05224 */
    CMSG_SAVE_PLAYER                                 = 0x00,
    CMSG_SETDEATHBINDPOINT                           = 0x00,
    SMSG_BINDPOINTUPDATE                             = 0x00, /* old 0x05080 */
    CMSG_GETDEATHBINDZONE                            = 0x00, /* old 0x03691 */
    SMSG_BINDZONEREPLY                               = 0x00, /* old 0x03EA2 */
    SMSG_PLAYERBOUND                                 = 0x00, /* old 0x07682 */
    SMSG_CLIENT_CONTROL_UPDATE                       = 0x00, /* old 0x07002 */
    CMSG_REPOP_REQUEST                               = 0x00, /* old 0x06206 */
    SMSG_RESURRECT_REQUEST                           = 0x00, /* old 0x04202 */
    CMSG_RESURRECT_RESPONSE                          = 0x00,
    CMSG_LOOT                                        = 0x00, /* old 0x05480 */
    CMSG_LOOT_MONEY                                  = 0x00, /* old 0x07A86 */
    CMSG_LOOT_RELEASE                                = 0x00, /* old 0x05C82 */
    SMSG_LOOT_RESPONSE                               = 0x00, /* old 0x01CA2 */
    SMSG_LOOT_RELEASE_RESPONSE                       = 0x00, /* old 0x00222 */
    SMSG_LOOT_REMOVED                                = 0x00, /* old 0x07080 */
    SMSG_LOOT_MONEY_NOTIFY                           = 0x00, /* old 0x01E02 */
    SMSG_LOOT_ITEM_NOTIFY                            = 0x00, /* old 0x05E02 */
    SMSG_LOOT_CLEAR_MONEY                            = 0x00, /* old 0x07802 */
    SMSG_ITEM_PUSH_RESULT                            = 0x00, /* old 0x06220 */
    SMSG_DUEL_REQUESTED                              = 0x00, /* old 0x00C24 */
    SMSG_DUEL_OUTOFBOUNDS                            = 0x00, /* old 0x06C24 */
    SMSG_DUEL_INBOUNDS                               = 0x00, /* old 0x06406 */
    SMSG_DUEL_COMPLETE                               = 0x00, /* old 0x044A4 */
    SMSG_DUEL_WINNER                                 = 0x00, /* old 0x07086 */
    CMSG_DUEL_ACCEPTED                               = 0x00, /* old 0x03824 */
    CMSG_DUEL_CANCELLED                              = 0x00, /* old 0x034A6 */
    SMSG_MOUNTRESULT                                 = 0x00, /* old 0x07A00 */
    SMSG_DISMOUNTRESULT                              = 0x00, /* old 0x046A2 */
    SMSG_PUREMOUNT_CANCELLED_OBSOLETE                = 0x00,
    CMSG_MOUNTSPECIAL_ANIM                           = 0x00, /* old 0x01A00 */
    SMSG_MOUNTSPECIAL_ANIM                           = 0x0656B, /* old 0x07AA6 */
    SMSG_PET_TAME_FAILURE                            = 0x00, /* old 0x05620 */
    CMSG_PET_SET_ACTION                              = 0x00, /* old 0x03E22 */
    CMSG_PET_ACTION                                  = 0x00,
    CMSG_PET_ABANDON                                 = 0x00,
    CMSG_PET_RENAME                                  = 0x00,
    SMSG_PET_NAME_INVALID                            = 0x00,
    SMSG_PET_SPELLS                                  = 0x06583
    SMSG_PET_MODE                                    = 0x00,
    CMSG_GOSSIP_HELLO                                = 0x00, /* old 0x03622 */
    CMSG_GOSSIP_SELECT_OPTION                        = 0x00, /* old 0x00280 */
    SMSG_GOSSIP_MESSAGE                              = 0x00, /* old 0x06082 */
    SMSG_GOSSIP_COMPLETE                             = 0x00, /* old 0x02E82 */
    CMSG_NPC_TEXT_QUERY                              = 0x04DF3,
    SMSG_NPC_TEXT_UPDATE                             = 0x00, /* old 0x000A0 */
    SMSG_NPC_WONT_TALK                               = 0x00,
    CMSG_QUESTGIVER_STATUS_QUERY                     = 0x00, /* old 0x07E86 */
    SMSG_QUESTGIVER_STATUS                           = 0x00, /* old 0x07A22 */
    CMSG_QUESTGIVER_HELLO                            = 0x00,
    SMSG_QUESTGIVER_QUEST_LIST                       = 0x00,
    CMSG_QUESTGIVER_QUERY_QUEST                      = 0x00,
    CMSG_QUESTGIVER_QUEST_AUTOLAUNCH                 = 0x00,
    SMSG_QUESTGIVER_QUEST_DETAILS                    = 0x00,
    CMSG_QUESTGIVER_ACCEPT_QUEST                     = 0x00,
    CMSG_QUESTGIVER_COMPLETE_QUEST                   = 0x00,
    SMSG_QUESTGIVER_REQUEST_ITEMS                    = 0x00, /* old 0x03C24 */
    CMSG_QUESTGIVER_REQUEST_REWARD                   = 0x00,
    SMSG_QUESTGIVER_OFFER_REWARD                     = 0x00,
    CMSG_QUESTGIVER_CHOOSE_REWARD                    = 0x00,
    SMSG_QUESTGIVER_QUEST_INVALID                    = 0x00,
    CMSG_QUESTGIVER_CANCEL                           = 0x00,
    SMSG_QUESTGIVER_QUEST_COMPLETE                   = 0x00,
    SMSG_QUESTGIVER_QUEST_FAILED                     = 0x00,
    CMSG_QUESTLOG_SWAP_QUEST                         = 0x00,
    CMSG_QUESTLOG_REMOVE_QUEST                       = 0x00,
    SMSG_QUESTLOG_FULL                               = 0x00,
    SMSG_QUESTUPDATE_FAILED                          = 0x00,
    SMSG_QUESTUPDATE_FAILEDTIMER                     = 0x00,
    SMSG_QUESTUPDATE_COMPLETE                        = 0x00,
    SMSG_QUESTUPDATE_ADD_KILL                        = 0x00, /* old 0x02082 */
    SMSG_QUESTUPDATE_ADD_ITEM                        = 0x00,
    CMSG_QUEST_CONFIRM_ACCEPT                        = 0x00,
    SMSG_QUEST_CONFIRM_ACCEPT                        = 0x00,
    CMSG_PUSHQUESTTOPARTY                            = 0x00, /* old 0x04624 */
    CMSG_LIST_INVENTORY                              = 0x00, /* old 0x04026 */
    SMSG_LIST_INVENTORY                              = 0x00, /* old 0x0242E */
    CMSG_SELL_ITEM                                   = 0x00, /* old 0x03000 */
    SMSG_SELL_ITEM                                   = 0x00, /* old 0x04C02 */
    CMSG_BUY_ITEM                                    = 0x00, /* old 0x01086 */
    SMSG_BUY_ITEM                                    = 0x00, /* old 0x07E20 */
    SMSG_BUY_FAILED                                  = 0x00, /* old 0x00C3E */
    CMSG_TAXICLEARALLNODES                           = 0x00,
    CMSG_TAXIENABLEALLNODES                          = 0x00,
    CMSG_TAXISHOWNODES                               = 0x00,
    SMSG_SHOWTAXINODES                               = 0x00,
    CMSG_TAXINODE_STATUS_QUERY                       = 0x00,
    SMSG_TAXINODE_STATUS                             = 0x00,
    CMSG_TAXIQUERYAVAILABLENODES                     = 0x00,
    CMSG_ACTIVATETAXI                                = 0x00,
    SMSG_ACTIVATETAXIREPLY                           = 0x00,
    SMSG_NEW_TAXI_PATH                               = 0x00,
    CMSG_TRAINER_LIST                                = 0x00,
    SMSG_TRAINER_LIST                                = 0x00, /* old 0x04C80 */
    CMSG_TRAINER_BUY_SPELL                           = 0x00, /* old 0x07EA0 */
    SMSG_TRAINER_BUY_RESULT                          = 0x00, /* old 0x0460C - Possible - or 0x03C20 */
    CMSG_BINDER_ACTIVATE                             = 0x00,
    SMSG_PLAYERBINDERROR                             = 0x00,
    CMSG_BANKER_ACTIVATE                             = 0x00,
    SMSG_SHOW_BANK                                   = 0x00, /* old 0x04A24 */
    CMSG_BUY_BANK_SLOT                               = 0x00,
    SMSG_BUY_BANK_SLOT_RESULT                        = 0x00,
    CMSG_PETITION_SHOWLIST                           = 0x00,
    SMSG_PETITION_SHOWLIST                           = 0x00,
    CMSG_PETITION_BUY                                = 0x00,
    CMSG_PETITION_SHOW_SIGNATURES                    = 0x00,
    SMSG_PETITION_SHOW_SIGNATURES                    = 0x00,
    CMSG_PETITION_SIGN                               = 0x00,
    SMSG_PETITION_SIGN_RESULTS                       = 0x00,
    MSG_PETITION_DECLINE                             = 0x00,
    CMSG_OFFER_PETITION                              = 0x00,
    CMSG_TURN_IN_PETITION                            = 0x00,
    SMSG_TURN_IN_PETITION_RESULTS                    = 0x00,
    CMSG_PETITION_QUERY                              = 0x00, /* old 0x07880 */
    SMSG_PETITION_QUERY_RESPONSE                     = 0x00, /* old 0x01C02 */
    SMSG_FISH_NOT_HOOKED                             = 0x00,
    SMSG_FISH_ESCAPED                                = 0x00,
    CMSG_BUG                                         = 0x00, /* old 0x05C06 */
    SMSG_NOTIFICATION                                = 0x00,
    CMSG_PLAYED_TIME                                 = 0x00, /* old 0x024A2 */
    SMSG_PLAYED_TIME                                 = 0x005AF, /* old 0x00002 */
    CMSG_QUERY_TIME                                  = 0x0257F, /* old 0x05200 */
    SMSG_QUERY_TIME_RESPONSE                         = 0x00, /* old 0x05882 */
    SMSG_LOG_XPGAIN                                  = 0x00, /* old 0x06C22 */
    SMSG_AURACASTLOG                                 = 0x00,
    CMSG_RECLAIM_CORPSE                              = 0x00, /* old 0x04282 */
    CMSG_WRAP_ITEM                                   = 0x00,
    SMSG_LEVELUP_INFO                                = 0x00, /* old 0x05EA4 */
    MSG_MINIMAP_PING                                 = 0x00,
    SMSG_RESISTLOG                                   = 0x00,
    SMSG_ENCHANTMENTLOG                              = 0x00,
    CMSG_SET_SKILL_CHEAT                             = 0x00,
    SMSG_START_MIRROR_TIMER                          = 0x00,
    SMSG_PAUSE_MIRROR_TIMER                          = 0x00,
    SMSG_STOP_MIRROR_TIMER                           = 0x00, /* old 0x02C02 */
    CMSG_PING                                        = 0x0404A,
    SMSG_PONG                                        = 0x00108,
    SMSG_CLEAR_COOLDOWN                              = 0x00,
    SMSG_GAMEOBJECT_PAGETEXT                         = 0x00,
    CMSG_SETSHEATHED                                 = 0x00, /* old 0x04400 */
    SMSG_COOLDOWN_CHEAT                              = 0x00,
    SMSG_SPELL_DELAYED                               = 0x00,
    CMSG_QUEST_POI_QUERY                             = 0x00, /* old 0x02620 */
    SMSG_QUEST_POI_QUERY_RESPONSE                    = 0x005C1,
    CMSG_GHOST                                       = 0x00,
    CMSG_GM_INVIS                                    = 0x00,
    SMSG_INVALID_PROMOTION_CODE                      = 0x00,
    MSG_GM_BIND_OTHER                                = 0x00,
    MSG_GM_SUMMON                                    = 0x00,
    SMSG_ITEM_TIME_UPDATE                            = 0x00, /* old 0x03C82 */
    SMSG_ITEM_ENCHANT_TIME_UPDATE                    = 0x00, /* old 0x03626 */
    SMSG_AUTH_CHALLENGE                              = 0x00129, // 4.3.2 15211
    CMSG_AUTH_SESSION                                = 0x04042, // 4.3.2 15211
    SMSG_AUTH_RESPONSE                               = 0x00E54, // 4.3.2 15211
    MSG_GM_SHOWLABEL                                 = 0x00,
    CMSG_PET_CAST_SPELL                              = 0x00,
    MSG_SAVE_GUILD_EMBLEM                            = 0x00,
    MSG_TABARDVENDOR_ACTIVATE                        = 0x00,
    SMSG_PLAY_SPELL_VISUAL                           = 0x01CB4,
    CMSG_ZONEUPDATE                                  = 0x00, /* old 0x03600 */
    SMSG_PARTYKILLLOG                                = 0x00, /* old 0x06886 */
    SMSG_COMPRESSED_UPDATE_OBJECT                    = 0x00, /* old 0x01CC3 */
    SMSG_PLAY_SPELL_IMPACT                           = 0x00, /* old 0x00220 */
    SMSG_EXPLORATION_EXPERIENCE                      = 0x00,
    CMSG_GM_SET_SECURITY_GROUP                       = 0x00,
    CMSG_GM_NUKE                                     = 0x00,
    MSG_RANDOM_ROLL                                  = 0x00,
    SMSG_ENVIRONMENTALDAMAGELOG                      = 0x00,
    CMSG_PLAYER_DIFFICULTY_CHANGE                    = 0x00,
    SMSG_RWHOIS                                      = 0x00,
    SMSG_LFG_PLAYER_REWARD                           = 0x00,
    SMSG_LFG_TELEPORT_DENIED                         = 0x00,
    CMSG_UNLEARN_SPELL                               = 0x00,
    CMSG_UNLEARN_SKILL                               = 0x00,
    SMSG_REMOVED_SPELL                               = 0x00,
    CMSG_DECHARGE                                    = 0x00,
    CMSG_GMTICKET_CREATE                             = 0x00, /* old 0x06C82 */
    SMSG_GMTICKET_CREATE                             = 0x00, /* old 0x06CA4 */
    CMSG_GMTICKET_UPDATETEXT                         = 0x00, /* old 0x032A0 */
    SMSG_GMTICKET_UPDATETEXT                         = 0x00, /* old 0x01C84 */
    SMSG_ACCOUNT_DATA_TIMES                          = 0x0058B, // 4.3.2 15211
    CMSG_REQUEST_ACCOUNT_DATA                        = 0x00, /* old 0x04002 */
    CMSG_UPDATE_ACCOUNT_DATA                         = 0x00, /* old 0x002A0 */
    SMSG_UPDATE_ACCOUNT_DATA                         = 0x00, /* old 0x01EA3 */
    SMSG_CLEAR_FAR_SIGHT_IMMEDIATE                   = 0x00,
    SMSG_PLAYER_DIFFICULTY_CHANGE                    = 0x00,
    CMSG_GM_TEACH                                    = 0x00,
    CMSG_GM_CREATE_ITEM_TARGET                       = 0x00,
    CMSG_GMTICKET_GETTICKET                          = 0x00,
    SMSG_GMTICKET_GETTICKET                          = 0x00, /* old 0x01880 */
    CMSG_UNLEARN_TALENTS                             = 0x00,
    SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT              = 0x00,
    SMSG_GAMEOBJECT_DESPAWN_ANIM                     = 0x00,
    MSG_CORPSE_QUERY                                 = 0x00, /* old 0x05006 */
    CMSG_GMTICKET_DELETETICKET                       = 0x00, /* old 0x046AC */
    SMSG_GMTICKET_DELETETICKET                       = 0x00, /* old 0x060A6 */
    SMSG_CHAT_WRONG_FACTION                          = 0x00,
    CMSG_GMTICKET_SYSTEMSTATUS                       = 0x00,
    SMSG_GMTICKET_SYSTEMSTATUS                       = 0x02DFB,
    CMSG_SPIRIT_HEALER_ACTIVATE                      = 0x00, /* old 0x04024 */
    SMSG_QUEST_FORCE_REMOVED                         = 0x00,
    CMSG_SKILL_BUY_STEP                              = 0x00,
    CMSG_SKILL_BUY_RANK                              = 0x00,
    SMSG_SPIRIT_HEALER_CONFIRM                       = 0x00,
    CMSG_CHARACTER_POINT_CHEAT                       = 0x00,
    SMSG_GOSSIP_POI                                  = 0x00,
    CMSG_CHAT_IGNORED                                = 0x00,
    CMSG_GUILD_RANK                                  = 0x00, /* old 0x02A88 */
    SMSG_GUILD_RANK                                  = 0x00, /* old 0x06C1A */
    CMSG_GUILD_RANKS                                 = 0x01501,
    CMSG_GUILD_ADD_RANK                              = 0x00, /* old 0x00A8C */
    CMSG_GUILD_DEL_RANK                              = 0x00,
    CMSG_GUILD_SWITCH_RANK                           = 0x00,
    CMSG_GUILD_SET_NOTE                              = 0x00, /* old 0x00048 */
    CMSG_GUILD_QUERY_TRADESKILL                      = 0x00,
    SMSG_GUILD_CRITERIA_DELETED                      = 0x00,
    SMSG_LOGIN_VERIFY_WORLD                          = 0x00DEB, /* old 0x01C80 */
    CMSG_CLEAR_EXPLORATION                           = 0x00,
    CMSG_SEND_MAIL                                   = 0x05809,
    SMSG_SEND_MAIL_RESULT                            = 0x00DED, /* old 0x00C86 */
    CMSG_GET_MAIL_LIST                               = 0x00, /* old 0x05222 */
    SMSG_MAIL_LIST_RESULT                            = 0x025D3,
    CMSG_BATTLEFIELD_LIST                            = 0x023C4,
    SMSG_BATTLEFIELD_LIST                            = 0x00C51,
    CMSG_BATTLEFIELD_JOIN                            = 0x00,
    SMSG_JOINED_BATTLEGROUND_QUEUE                   = 0x00,
    CMSG_REQUEST_RATED_BG_INFO                       = 0x00001,
    CMSG_REQUEST_PVP_OPTIONS_ENABLED                 = 0x00840,
    CMSG_JOIN_RATED_BATTLEFIELD                      = 0x00,
    CMSG_ITEM_TEXT_QUERY                             = 0x00, /* old 0x07620 */
    SMSG_ITEM_TEXT_QUERY_RESPONSE                    = 0x00, /* old 0x016A4 */
    CMSG_MAIL_TAKE_MONEY                             = 0x00, /* old 0x06426 */
    CMSG_MAIL_TAKE_ITEM                              = 0x00, /* old 0x07C06 */
    CMSG_MAIL_MARK_AS_READ                           = 0x00,
    CMSG_MAIL_RETURN_TO_SENDER                       = 0x00,
    CMSG_MAIL_DELETE                                 = 0x00, /* old 0x01E26 */
    CMSG_MAIL_CREATE_TEXT_ITEM                       = 0x00, /* old 0x01082 */
    SMSG_SPELLLOGMISS                                = 0x00,
    SMSG_SPELLLOGEXECUTE                             = 0x04569, /* old 0x03A82 */
    SMSG_DEBUGAURAPROC                               = 0x00,
    SMSG_PERIODICAURALOG                             = 0x00, /* old 0x03486 */
    SMSG_SPELLDAMAGESHIELD                           = 0x00,
    SMSG_SPELLNONMELEEDAMAGELOG                      = 0x0250F,
    CMSG_LEARN_TALENT                                = 0x00,
    SMSG_RESURRECT_FAILED                            = 0x00,
    CMSG_TOGGLE_PVP                                  = 0x00,
    SMSG_ZONE_UNDER_ATTACK                           = 0x06D29,
    MSG_AUCTION_HELLO                                = 0x00, /* old 0x00680 */
    CMSG_AUCTION_SELL_ITEM                           = 0x00,
    CMSG_AUCTION_REMOVE_ITEM                         = 0x00,
    CMSG_AUCTION_LIST_ITEMS                          = 0x00, /* old 0x02C26 */
    CMSG_AUCTION_LIST_OWNER_ITEMS                    = 0x00, /* old 0x01422 */
    CMSG_AUCTION_PLACE_BID                           = 0x00,
    SMSG_AUCTION_COMMAND_RESULT                      = 0x005F7,
    SMSG_AUCTION_LIST_RESULT                         = 0x04507,
    SMSG_AUCTION_OWNER_LIST_RESULT                   = 0x06D69,
    SMSG_AUCTION_BIDDER_NOTIFICATION                 = 0x0257B,
    SMSG_AUCTION_OWNER_NOTIFICATION                  = 0x00, /* old 0x032A4 */
    SMSG_PROCRESIST                                  = 0x00,
    SMSG_STANDSTATE_CHANGE_FAILURE_OBSOLETE          = 0x00,
    SMSG_DISPEL_FAILED                               = 0x00,
    SMSG_SPELLORDAMAGE_IMMUNE                        = 0x00,
    CMSG_AUCTION_LIST_BIDDER_ITEMS                   = 0x00, /* old 0x07A04 */
    SMSG_AUCTION_BIDDER_LIST_RESULT                  = 0x06517,
    SMSG_SET_FLAT_SPELL_MODIFIER                     = 0x00, /* old 0x04686 */
    SMSG_SET_PCT_SPELL_MODIFIER                      = 0x00, /* old 0x064A2 */
    CMSG_SET_AMMO                                    = 0x00,
    SMSG_CORPSE_RECLAIM_DELAY                        = 0x00, /* old 0x04404 */
    CMSG_SET_ACTIVE_MOVER                            = 0x02384, /* old 0x06693 */
    CMSG_PET_CANCEL_AURA                             = 0x00, /* old 0x026A0 */
    CMSG_PLAYER_AI_CHEAT                             = 0x00,
    CMSG_CANCEL_AUTO_REPEAT_SPELL                    = 0x00,
    MSG_GM_ACCOUNT_ONLINE                            = 0x00,
    MSG_LIST_STABLED_PETS                            = 0x00,
    SMSG_STABLE_RESULT                               = 0x00,
    CMSG_STABLE_REVIVE_PET                           = 0x00,
    CMSG_STABLE_CHANGE_SLOT                          = 0x00,
    MSG_QUEST_PUSH_RESULT                            = 0x00,
    SMSG_PLAY_MUSIC                                  = 0x0256D, // 4.3.2 15211
    SMSG_PLAY_OBJECT_SOUND                           = 0x0451F, // 4.3.2 15211
    CMSG_REQUEST_PET_INFO                            = 0x00,
    CMSG_FAR_SIGHT                                   = 0x00,
    SMSG_SPELLDISPELLOG                              = 0x00,
    SMSG_DAMAGE_CALC_LOG                             = 0x00,
    CMSG_ENABLE_DAMAGE_LOG                           = 0x00,
    CMSG_GROUP_CHANGE_SUB_GROUP                      = 0x00,
    CMSG_REQUEST_PARTY_MEMBER_STATS                  = 0x00,
    CMSG_GROUP_SWAP_SUB_GROUP                        = 0x00,
    CMSG_RESET_FACTION_CHEAT                         = 0x00,
    CMSG_AUTOSTORE_BANK_ITEM                         = 0x00,
    CMSG_AUTOBANK_ITEM                               = 0x00,
    MSG_QUERY_NEXT_MAIL_TIME                         = 0x2DB5, /* old 0x02880 */
    SMSG_RECEIVED_MAIL                               = 0x00, /* old 0x00CA0 */
    SMSG_RAID_GROUP_ONLY                             = 0x00,
    CMSG_SET_DURABILITY_CHEAT                        = 0x00,
    CMSG_SET_PVP_RANK_CHEAT                          = 0x00,
    CMSG_ADD_PVP_MEDAL_CHEAT                         = 0x00,
    CMSG_DEL_PVP_MEDAL_CHEAT                         = 0x00,
    CMSG_SET_PVP_TITLE                               = 0x00,
    SMSG_PVP_CREDIT                                  = 0x00,
    SMSG_AUCTION_REMOVED_NOTIFICATION                = 0x00, /* old 0x00A86 */
    CMSG_GROUP_RAID_CONVERT                          = 0x00,
    CMSG_GROUP_ASSISTANT_LEADER                      = 0x00,
    CMSG_BUYBACK_ITEM                                = 0x00, /* old 0x04AA6 */
    SMSG_SERVER_MESSAGE                              = 0x00, /* old 0x01084 */
    CMSG_SET_SAVED_INSTANCE_EXTEND                   = 0x00,
    SMSG_LFG_OFFER_CONTINUE                          = 0x00,
    CMSG_MEETINGSTONE_CHEAT                          = 0x00,
    SMSG_MEETINGSTONE_SETQUEUE                       = 0x00,
    CMSG_MEETINGSTONE_INFO                           = 0x00,
    SMSG_MEETINGSTONE_COMPLETE                       = 0x00,
    SMSG_MEETINGSTONE_IN_PROGRESS                    = 0x00,
    SMSG_MEETINGSTONE_MEMBER_ADDED                   = 0x00,
    CMSG_GMTICKETSYSTEM_TOGGLE                       = 0x00,
    CMSG_CANCEL_GROWTH_AURA                          = 0x00, /* old 0x06A80 */
    SMSG_CANCEL_AUTO_REPEAT                          = 0x0655B,
    SMSG_STANDSTATE_UPDATE                           = 0x025DF,
    SMSG_LOOT_ALL_PASSED                             = 0x00,
    SMSG_LOOT_ROLL_WON                               = 0x00,
    CMSG_LOOT_ROLL                                   = 0x00,
    SMSG_LOOT_START_ROLL                             = 0x00,
    SMSG_LOOT_ROLL                                   = 0x00,
    CMSG_LOOT_MASTER_GIVE                            = 0x01D81,
    SMSG_LOOT_MASTER_LIST                            = 0x00, /* old 0x02200 */
    SMSG_SET_FORCED_REACTIONS                        = 0x00, /* old 0x04A20 */
    SMSG_SPELL_FAILED_OTHER                          = 0x00,
    SMSG_GAMEOBJECT_RESET_STATE                      = 0x00,
    CMSG_REPAIR_ITEM                                 = 0x00, /* old 0x00080 */
    SMSG_CHAT_PLAYER_NOT_FOUND                       = 0x00,
    MSG_TALENT_WIPE_CONFIRM                          = 0x00,
    SMSG_SUMMON_REQUEST                              = 0x00,
    CMSG_SUMMON_RESPONSE                             = 0x00,
    MSG_MOVE_TOGGLE_GRAVITY_CHEAT                    = 0x00,
    SMSG_MONSTER_MOVE_TRANSPORT                      = 0x00,
    SMSG_PET_BROKEN                                  = 0x00,
    MSG_MOVE_FEATHER_FALL                            = 0x00,
    MSG_MOVE_WATER_WALK                              = 0x00,
    CMSG_SERVER_BROADCAST                            = 0x00,
    CMSG_SELF_RES                                    = 0x00, /* old 0x028A0 */
    SMSG_FEIGN_DEATH_RESISTED                        = 0x00,
    CMSG_RUN_SCRIPT                                  = 0x00,
    SMSG_SCRIPT_MESSAGE                              = 0x00,
    SMSG_DUEL_COUNTDOWN                              = 0x00, /* old 0x07420 */
    SMSG_AREA_TRIGGER_MESSAGE                        = 0x00,
    CMSG_SHOWING_HELM                                = 0x00, /* old 0x000A2 */
    CMSG_SHOWING_CLOAK                               = 0x00, /* old 0x03826 */
    SMSG_LFG_ROLE_CHOSEN                             = 0x00,
    SMSG_PLAYER_SKINNED                              = 0x00,
    SMSG_DURABILITY_DAMAGE_DEATH                     = 0x00, /* old 0x07684 */
    CMSG_SET_EXPLORATION                             = 0x00,
    CMSG_SET_ACTIONBAR_TOGGLES                       = 0x00, /* old 0x076A4 */
    MSG_PETITION_RENAME                              = 0x00,
    SMSG_INIT_WORLD_STATES                           = 0x00, /* old 0x03E80 */
    SMSG_UPDATE_WORLD_STATE                          = 0x00, /* old 0x04082 */
    CMSG_ITEM_NAME_QUERY                             = 0x00,
    SMSG_ITEM_NAME_QUERY_RESPONSE                    = 0x00,
    SMSG_PET_ACTION_FEEDBACK                         = 0x00,
    CMSG_CHAR_RENAME                                 = 0x00, /* old 0x06A04 */
    SMSG_CHAR_RENAME                                 = 0x00,
    CMSG_MOVE_SPLINE_DONE                            = 0x00BE0,
    CMSG_MOVE_FALL_RESET                             = 0x00, /* old 0x02683 */
    SMSG_INSTANCE_SAVE_CREATED                       = 0x00, /* old 0x01C04 */
    SMSG_RAID_INSTANCE_INFO                          = 0x00, /* old 0x05A00 */
    CMSG_REQUEST_RAID_INFO                           = 0x00, /* old 0x07A82 */
    CMSG_MOVE_TIME_SKIPPED                           = 0x00,
    CMSG_MOVE_FEATHER_FALL_ACK                       = 0x00, /* old 0x03223 */
    CMSG_MOVE_WATER_WALK_ACK                         = 0x00BA1,
    CMSG_MOVE_NOT_ACTIVE_MOVER                       = 0x00, /* old 0x070A3 */
    SMSG_PLAY_SOUND                                  = 0x02DE5, // 4.3.2 15211
    CMSG_BATTLEFIELD_STATUS                          = 0x05040,
    SMSG_BATTLEFIELD_STATUS1                         = 0x00CC1,
    SMSG_BATTLEFIELD_STATUS2                         = 0x00C81,
    SMSG_BATTLEFIELD_STATUS3                         = 0x01CA1, // SMSG_BATTLEFIELD_STATUS_ACTIVE?????
    SMSG_BATTLEFIELD_STATUS4                         = 0x00E25,
    CMSG_BATTLEFIELD_PORT                            = 0x02901,
    CMSG_INSPECT_HONOR_STATS                         = 0x00,
    SMSG_INSPECT_HONOR_STATS                         = 0x00, /* old 0x06C9A */
    CMSG_BATTLEMASTER_HELLO                          = 0x00,
    CMSG_MOVE_START_SWIM_CHEAT                       = 0x00,
    CMSG_MOVE_STOP_SWIM_CHEAT                        = 0x00,
    SMSG_FORCE_WALK_SPEED_CHANGE                     = 0x00,
    CMSG_FORCE_WALK_SPEED_CHANGE_ACK                 = 0x00,
    SMSG_FORCE_SWIM_BACK_SPEED_CHANGE                = 0x00,
    CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK            = 0x02920,
    SMSG_FORCE_TURN_RATE_CHANGE                      = 0x00,
    CMSG_FORCE_TURN_RATE_CHANGE_ACK                  = 0x00,
    MSG_PVP_LOG_DATA                                 = 0x00C11,
    SMSG_PVP_RATED_STATS_UPDATE                      = 0x04018,
    CMSG_BATTLEFIELD_REQUEST_SCORE_DATA              = 0x00,
    CMSG_LEAVE_BATTLEFIELD                           = 0x02321,
    CMSG_AREA_SPIRIT_HEALER_QUERY                    = 0x00, /* old 0x032A2 */
    CMSG_AREA_SPIRIT_HEALER_QUEUE                    = 0x00, /* old 0x07826 */
    SMSG_AREA_SPIRIT_HEALER_TIME                     = 0x00, /* old 0x02A22 */
    CMSG_GM_UNTEACH                                  = 0x00,
    SMSG_WARDEN_DATA                                 = 0x00CF0, // 4.3.2 15211
    CMSG_WARDEN_DATA                                 = 0x04019,
    SMSG_GROUP_JOINED_BATTLEGROUND                   = 0x00, /* old 0x0469A */
    CMSG_BATTLEGROUND_PLAYER_POSITIONS               = 0x00B24,
    SMSG_BATTLEGROUND_PLAYER_POSITIONS               = 0x01E75,
    CMSG_PET_STOP_ATTACK                             = 0x00,
    SMSG_BINDER_CONFIRM                              = 0x00,
    SMSG_BATTLEGROUND_PLAYER_JOINED                  = 0x00,
    SMSG_BATTLEGROUND_PLAYER_LEFT                    = 0x00,
    CMSG_BATTLEMASTER_JOIN                           = 0x00140,
    SMSG_ADDON_INFO                                  = 0x06D8D, // 4.3.2 15211
    CMSG_PET_UNLEARN                                 = 0x00,
    SMSG_PET_UNLEARN_CONFIRM                         = 0x00,
    SMSG_PARTY_MEMBER_STATS_FULL                     = 0x00,
    CMSG_PET_SPELL_AUTOCAST                          = 0x00,
    SMSG_WEATHER                                     = 0x00, /* old 0x068A2 */
    SMSG_PLAY_TIME_WARNING                           = 0x00,
    SMSG_MINIGAME_SETUP                              = 0x00,
    SMSG_MINIGAME_STATE                              = 0x00,
    CMSG_MINIGAME_MOVE                               = 0x00,
    SMSG_MINIGAME_MOVE_FAILED                        = 0x00,
    SMSG_RAID_INSTANCE_MESSAGE                       = 0x00, /* old 0x04802 */
    SMSG_COMPRESSED_MOVES                            = 0x00,
    CMSG_GUILD_INFO_TEXT                             = 0x00, /* old 0x02088 */
    SMSG_GUILD_PARTY_STATE_UPDATE                    = 0x00E91,
    SMSG_CHAT_RESTRICTED                             = 0x00,
    SMSG_SPLINE_SET_RUN_SPEED                        = 0x01434,
    SMSG_SPLINE_SET_RUN_BACK_SPEED                   = 0x00,
    SMSG_SPLINE_SET_SWIM_SPEED                       = 0x00,
    SMSG_SPLINE_SET_WALK_SPEED                       = 0x00,
    SMSG_SPLINE_SET_SWIM_BACK_SPEED                  = 0x00,
    SMSG_SPLINE_SET_TURN_RATE                        = 0x00,
    SMSG_SPLINE_MOVE_UNROOT                          = 0x00,
    SMSG_SPLINE_MOVE_FEATHER_FALL                    = 0x00,
    SMSG_SPLINE_MOVE_NORMAL_FALL                     = 0x00,
    SMSG_SPLINE_MOVE_SET_HOVER                       = 0x00,
    SMSG_SPLINE_MOVE_UNSET_HOVER                     = 0x00,
    SMSG_SPLINE_MOVE_WATER_WALK                      = 0x00,
    SMSG_SPLINE_MOVE_LAND_WALK                       = 0x00,
    SMSG_SPLINE_MOVE_START_SWIM                      = 0x00,
    SMSG_SPLINE_MOVE_STOP_SWIM                       = 0x00,
    SMSG_SPLINE_MOVE_SET_RUN_MODE                    = 0x00,
    SMSG_SPLINE_MOVE_SET_WALK_MODE                   = 0x00,
    CMSG_GM_NUKE_ACCOUNT                             = 0x00,
    MSG_GM_DESTROY_CORPSE                            = 0x00,
    CMSG_GM_DESTROY_ONLINE_CORPSE                    = 0x00,
    CMSG_ACTIVATETAXIEXPRESS                         = 0x00,
    SMSG_SET_FACTION_ATWAR                           = 0x00,
    SMSG_GAMETIMEBIAS_SET                            = 0x00,
    CMSG_DEBUG_ACTIONS_START                         = 0x00,
    CMSG_DEBUG_ACTIONS_STOP                          = 0x00,
    CMSG_SET_FACTION_INACTIVE                        = 0x00,
    CMSG_SET_WATCHED_FACTION                         = 0x00,
    MSG_MOVE_TIME_SKIPPED                            = 0x01C01,
    SMSG_SPLINE_MOVE_ROOT                            = 0x00,
    CMSG_SET_EXPLORATION_ALL                         = 0x00,
    SMSG_INVALIDATE_PLAYER                           = 0x00, /* old 0x07484 */
    CMSG_RESET_INSTANCES                             = 0x00,
    SMSG_INSTANCE_RESET                              = 0x00,
    SMSG_INSTANCE_RESET_FAILED                       = 0x00,
    SMSG_UPDATE_LAST_INSTANCE                        = 0x00,
    MSG_RAID_TARGET_UPDATE                           = 0x00,
    MSG_RAID_READY_CHECK                             = 0x02523,
    SMSG_RAID_READY_CHECK_THROTTLED                  = 0x00,
    CMSG_LUA_USAGE                                   = 0x00,
    SMSG_PET_ACTION_SOUND                            = 0x02D55,
    SMSG_PET_DISMISS_SOUND                           = 0x00,
    SMSG_GHOSTEE_GONE                                = 0x00,
    CMSG_GM_UPDATE_TICKET_STATUS                     = 0x00,
    SMSG_GM_TICKET_STATUS_UPDATE                     = 0x00,
    MSG_SET_DUNGEON_DIFFICULTY                       = 0x02597, /* old 0x07006 */
    CMSG_GMSURVEY_SUBMIT                             = 0x00,
    SMSG_UPDATE_INSTANCE_OWNERSHIP                   = 0x00,
    CMSG_IGNORE_KNOCKBACK_CHEAT                      = 0x00,
    SMSG_CHAT_PLAYER_AMBIGUOUS                       = 0x00,
    MSG_DELAY_GHOST_TELEPORT                         = 0x00,
    SMSG_SPELLINSTAKILLLOG                           = 0x00,
    SMSG_SPELL_UPDATE_CHAIN_TARGETS                  = 0x00,
    CMSG_CHAT_FILTERED                               = 0x00,
    SMSG_EXPECTED_SPAM_RECORDS                       = 0x00,
    SMSG_SPELLSTEALLOG                               = 0x00,
    CMSG_LOTTERY_QUERY_OBSOLETE                      = 0x00,
    SMSG_LOTTERY_QUERY_RESULT_OBSOLETE               = 0x00,
    CMSG_BUY_LOTTERY_TICKET_OBSOLETE                 = 0x00,
    SMSG_LOTTERY_RESULT_OBSOLETE                     = 0x00,
    SMSG_CHARACTER_PROFILE                           = 0x00,
    SMSG_CHARACTER_PROFILE_REALM_CONNECTED           = 0x00,
    SMSG_DEFENSE_MESSAGE                             = 0x00,
    SMSG_INSTANCE_DIFFICULTY                         = 0x00,
    MSG_GM_RESETINSTANCELIMIT                        = 0x00,
    SMSG_MOTD                                        = 0x06D11, /* old 0x04884 */
    SMSG_MOVE_SET_FLIGHT                             = 0x00,
    SMSG_MOVE_UNSET_FLIGHT                           = 0x00,
    CMSG_MOVE_FLIGHT_ACK                             = 0x00,
    MSG_MOVE_START_SWIM_CHEAT                        = 0x00,
    MSG_MOVE_STOP_SWIM_CHEAT                         = 0x00,
    SMSG_MOVE_SET_CAN_FLY                            = 0x00, /* old 0x0440C */
    SMSG_MOVE_UNSET_CAN_FLY                          = 0x00451,
    CMSG_MOVE_SET_CAN_FLY_ACK                        = 0x021C0,
    CMSG_MOVE_SET_FLY                                = 0x00, /* old 0x02421 */
    CMSG_SOCKET_GEMS                                 = 0x00,
    CMSG_ARENA_TEAM_CREATE                           = 0x05840,
    SMSG_ARENA_TEAM_COMMAND_RESULT                   = 0x014F4,
    CMSG_ARENA_TEAM_QUERY                            = 0x02507,
    SMSG_ARENA_TEAM_QUERY_RESPONSE                   = 0x02D0B,
    CMSG_ARENA_TEAM_ROSTER                           = 0x00,
    SMSG_ARENA_TEAM_ROSTER                           = 0x00DF7,
    CMSG_ARENA_TEAM_INVITE                           = 0x00,
    SMSG_ARENA_TEAM_INVITE                           = 0x00, /* old 0x03A26 */
    CMSG_ARENA_TEAM_ACCEPT                           = 0x00,
    CMSG_ARENA_TEAM_DECLINE                          = 0x00,
    CMSG_ARENA_TEAM_LEAVE                            = 0x00,
    CMSG_ARENA_TEAM_REMOVE                           = 0x00,
    CMSG_ARENA_TEAM_DISBAND                          = 0x00,
    CMSG_ARENA_TEAM_LEADER                           = 0x00,
    SMSG_ARENA_TEAM_EVENT                            = 0x00,
    CMSG_BATTLEMASTER_JOIN_ARENA                     = 0x00,
    MSG_MOVE_START_ASCEND                            = 0x00,
    MSG_MOVE_STOP_ASCEND                             = 0x00,
    SMSG_ARENA_TEAM_STATS                            = 0x0059B,
    CMSG_LFG_JOIN                                    = 0x01059,
    CMSG_LFG_LEAVE                                   = 0x00, /* old 0x04306,  // 4.3.0 15050 */
    CMSG_SEARCH_LFG_JOIN                             = 0x00,
    CMSG_SEARCH_LFG_LEAVE                            = 0x00,
    SMSG_UPDATE_LFG_LIST                             = 0x00,
    SMSG_LFG_PROPOSAL_UPDATE                         = 0x00,
    CMSG_LFG_PROPOSAL_RESULT                         = 0x00,
    SMSG_LFG_ROLE_CHECK_UPDATE                       = 0x00,
    SMSG_RAID_ROLE_CHECK_UPDATE                      = 0x00,
    SMSG_LFG_JOIN_RESULT                             = 0x01C20,
    SMSG_LFG_QUEUE_STATUS                            = 0x00,
    CMSG_SET_LFG_COMMENT                             = 0x05811,
    SMSG_LFG_UPDATE_PLAYER                           = 0x00,
    SMSG_LFG_UPDATE_PARTY                            = 0x00,
    SMSG_LFG_UPDATE_LIST                             = 0x00,
    CMSG_LFG_SET_ROLES                               = 0x00,
    CMSG_LFG_SET_NEEDS                               = 0x00,
    CMSG_LFG_SET_BOOT_VOTE                           = 0x00,
    SMSG_LFG_BOOT_PROPOSAL_UPDATE                    = 0x00,
    CMSG_LFD_PLAYER_LOCK_INFO_REQUEST                = 0x00,
    SMSG_LFG_PLAYER_INFO                             = 0x00,
    CMSG_LFG_TELEPORT                                = 0x00, /* old 0x00366 */
    CMSG_LFD_PARTY_LOCK_INFO_REQUEST                 = 0x00,
    SMSG_LFG_PARTY_INFO                              = 0x00,
    SMSG_TITLE_EARNED                                = 0x00,
    CMSG_SET_TITLE                                   = 0x00,
    CMSG_CANCEL_MOUNT_AURA                           = 0x00, /* old 0x05A80 */
    SMSG_ARENA_ERROR                                 = 0x00,
    MSG_INSPECT_ARENA_TEAMS                          = 0x00,
    SMSG_DEATH_RELEASE_LOC                           = 0x00, /* old 0x03A84 */
    CMSG_CANCEL_TEMP_ENCHANTMENT                     = 0x00,
    SMSG_FORCED_DEATH_UPDATE                         = 0x00, /* old 0x06400 */
    CMSG_CHEAT_SET_HONOR_CURRENCY                    = 0x00,
    CMSG_CHEAT_SET_ARENA_CURRENCY                    = 0x00,
    SMSG_INIT_CURRENCY                               = 0x01600,
    SMSG_UPDATE_CURRENCY                             = 0x01600, // SMSG_SETUP_CURRENCY ????????
    SMSG_UPDATE_CURRENCY_WEEK_LIMIT                  = 0x00, /* old 0x0443A */
    MSG_MOVE_SET_FLIGHT_SPEED_CHEAT                  = 0x00,
    MSG_MOVE_SET_FLIGHT_SPEED                        = 0x00465,
    MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT             = 0x00,
    MSG_MOVE_SET_FLIGHT_BACK_SPEED                   = 0x00,
    SMSG_FORCE_FLIGHT_SPEED_CHANGE                   = 0x00,
    CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK               = 0x00,
    SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE              = 0x00,
    CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK          = 0x00,
    SMSG_SPLINE_SET_FLIGHT_SPEED                     = 0x00,
    SMSG_SPLINE_SET_FLIGHT_BACK_SPEED                = 0x00,
    CMSG_MAELSTROM_INVALIDATE_CACHE                  = 0x00,
    SMSG_FLIGHT_SPLINE_SYNC                          = 0x06533,
    CMSG_SET_TAXI_BENCHMARK_MODE                     = 0x00,
    SMSG_REALM_SPLIT                                 = 0x00581,
    CMSG_REALM_SPLIT                                 = 0x00DB7, // 4.3.2 15211
    CMSG_MOVE_CHNG_TRANSPORT                         = 0x00,
    MSG_PARTY_ASSIGNMENT                             = 0x00,
    SMSG_OFFER_PETITION_ERROR                        = 0x00,
    SMSG_TIME_SYNC_REQ                               = 0x00C20, /* old 0x0661E */
    CMSG_TIME_SYNC_RESP                              = 0x00, /* old 0x07293 */
    CMSG_SEND_LOCAL_EVENT                            = 0x00,
    CMSG_SEND_GENERAL_TRIGGER                        = 0x00,
    CMSG_SEND_COMBAT_TRIGGER                         = 0x00,
    CMSG_MAELSTROM_GM_SENT_MAIL                      = 0x00,
    SMSG_RESET_FAILED_NOTIFY                         = 0x00,
    SMSG_REAL_GROUP_UPDATE                           = 0x00,
    SMSG_LFG_DISABLED                                = 0x00,
    CMSG_ACTIVE_PVP_CHEAT                            = 0x00,
    CMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY                 = 0x00,
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE        = 0x00,
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE_WRITE_FILE  = 0x00,
    SMSG_UPDATE_COMBO_POINTS                         = 0x00, /* old 0x02422 */
    SMSG_VOICE_SESSION_ROSTER_UPDATE                 = 0x00,
    SMSG_VOICE_SESSION_LEAVE                         = 0x04D75,
    SMSG_VOICE_SESSION_ADJUST_PRIORITY               = 0x00,
    CMSG_VOICE_SET_TALKER_MUTED_REQUEST              = 0x00,
    SMSG_VOICE_SET_TALKER_MUTED                      = 0x00,
    SMSG_INIT_EXTRA_AURA_INFO_OBSOLETE               = 0x00,
    SMSG_SET_EXTRA_AURA_INFO_OBSOLETE                = 0x00,
    SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE_OBSOLETE    = 0x00,
    SMSG_CLEAR_EXTRA_AURA_INFO_OBSOLETE              = 0x00,
    MSG_MOVE_START_DESCEND                           = 0x00,
    CMSG_IGNORE_REQUIREMENTS_CHEAT                   = 0x00,
    SMSG_IGNORE_REQUIREMENTS_CHEAT                   = 0x00,
    SMSG_SPELL_CHANCE_PROC_LOG                       = 0x00,
    CMSG_MOVE_SET_RUN_SPEED                          = 0x00,
    SMSG_DISMOUNT                                    = 0x005B9,
    MSG_MOVE_UPDATE_CAN_FLY                          = 0x00,
    MSG_RAID_READY_CHECK_CONFIRM                     = 0x06547,
    CMSG_VOICE_SESSION_ENABLE                        = 0x00, /* old 0x02A00 */
    SMSG_VOICE_SESSION_ENABLE                        = 0x00,
    SMSG_VOICE_PARENTAL_CONTROLS                     = 0x00,
    CMSG_GM_WHISPER                                  = 0x00,
    SMSG_GM_MESSAGECHAT                              = 0x00, /* old 0x00AA4 */
    MSG_GM_GEARRATING                                = 0x00,
    CMSG_COMMENTATOR_ENABLE                          = 0x00,
    SMSG_COMMENTATOR_STATE_CHANGED                   = 0x00,
    CMSG_COMMENTATOR_GET_MAP_INFO                    = 0x00,
    SMSG_COMMENTATOR_MAP_INFO                        = 0x00,
    CMSG_COMMENTATOR_GET_PLAYER_INFO                 = 0x00,
    SMSG_COMMENTATOR_GET_PLAYER_INFO                 = 0x00,
    SMSG_COMMENTATOR_PLAYER_INFO                     = 0x00,
    CMSG_COMMENTATOR_ENTER_INSTANCE                  = 0x00,
    CMSG_COMMENTATOR_EXIT_INSTANCE                   = 0x00,
    CMSG_COMMENTATOR_INSTANCE_COMMAND                = 0x00,
    SMSG_CLEAR_TARGET                                = 0x00,
    CMSG_BOT_DETECTED                                = 0x00,
    SMSG_CROSSED_INEBRIATION_THRESHOLD               = 0x00,
    CMSG_CHEAT_PLAYER_LOGIN                          = 0x00,
    CMSG_CHEAT_PLAYER_LOOKUP                         = 0x00,
    SMSG_CHEAT_PLAYER_LOOKUP                         = 0x00,
    SMSG_KICK_REASON                                 = 0x00, /* old 0x054A7 */
    MSG_RAID_READY_CHECK_FINISHED                    = 0x00,
    CMSG_COMPLAIN                                    = 0x00,
    SMSG_COMPLAIN_RESULT                             = 0x00,
    SMSG_FEATURE_SYSTEM_STATUS                       = 0x00EA5, /* old 0x04E2A */
    CMSG_GM_SHOW_COMPLAINTS                          = 0x00,
    CMSG_GM_UNSQUELCH                                = 0x00,
    CMSG_CHANNEL_SILENCE_VOICE                       = 0x00,
    CMSG_CHANNEL_SILENCE_ALL                         = 0x00,
    CMSG_CHANNEL_UNSILENCE_VOICE                     = 0x00,
    CMSG_CHANNEL_UNSILENCE_ALL                       = 0x00,
    CMSG_TARGET_CAST                                 = 0x00,
    CMSG_TARGET_SCRIPT_CAST                          = 0x00,
    CMSG_CHANNEL_DISPLAY_LIST                        = 0x00,
    CMSG_SET_ACTIVE_VOICE_CHANNEL                    = 0x00,
    CMSG_GET_CHANNEL_MEMBER_COUNT                    = 0x00,
    SMSG_CHANNEL_MEMBER_COUNT                        = 0x00,
    CMSG_CHANNEL_VOICE_ON                            = 0x00,
    CMSG_CHANNEL_VOICE_OFF                           = 0x00,
    CMSG_DEBUG_LIST_TARGETS                          = 0x00,
    SMSG_DEBUG_LIST_TARGETS                          = 0x00,
    SMSG_AVAILABLE_VOICE_CHANNEL                     = 0x00,
    CMSG_ADD_VOICE_IGNORE                            = 0x00,
    CMSG_DEL_VOICE_IGNORE                            = 0x00,
    CMSG_PARTY_SILENCE                               = 0x00,
    CMSG_PARTY_UNSILENCE                             = 0x00,
    MSG_NOTIFY_PARTY_SQUELCH                         = 0x00,
    SMSG_COMSAT_RECONNECT_TRY                        = 0x00,
    SMSG_COMSAT_DISCONNECT                           = 0x00,
    SMSG_COMSAT_CONNECT_FAIL                         = 0x00,
    SMSG_VOICE_CHAT_STATUS                           = 0x00,
    CMSG_REPORT_PVP_AFK                              = 0x00,
    SMSG_REPORT_PVP_AFK_RESULT                       = 0x00,
    CMSG_GUILD_BANKER_ACTIVATE                       = 0x00,
    CMSG_GUILD_BANK_QUERY_TAB                        = 0x00,
    SMSG_GUILD_BANK_LIST                             = 0x00,
    CMSG_GUILD_BANK_SWAP_ITEMS                       = 0x00, /* old 0x02AA4 */
    CMSG_GUILD_BANK_BUY_TAB                          = 0x00,
    CMSG_GUILD_BANK_UPDATE_TAB                       = 0x00,
    CMSG_GUILD_BANK_DEPOSIT_MONEY                    = 0x00,
    CMSG_GUILD_BANK_WITHDRAW_MONEY                   = 0x03585,
    CMSG_GUILD_BANK_NOTE                             = 0x00,
    MSG_GUILD_BANK_LOG_QUERY                         = 0x00,
    CMSG_SET_CHANNEL_WATCH                           = 0x00,
    SMSG_USERLIST_ADD                                = 0x00,
    SMSG_USERLIST_REM                             = 0x00,
    SMSG_USERLIST_UPDATE                             = 0x00,
    CMSG_CLEAR_CHANNEL_WATCH                         = 0x00,
    SMSG_INSPECT_TALENT                              = 0x00,
    SMSG_GOGOGO_OBSOLETE                             = 0x00,
    SMSG_ECHO_PARTY_SQUELCH                          = 0x00,
    CMSG_SET_TITLE_SUFFIX                            = 0x00,
    CMSG_SPELLCLICK                                  = 0x00,
    SMSG_LOOT_LIST                                   = 0x00,
    CMSG_GM_CHARACTER_RESTORE                        = 0x00,
    CMSG_GM_CHARACTER_SAVE                           = 0x00,
    SMSG_VOICESESSION_FULL                           = 0x00,
    MSG_GUILD_PERMISSIONS                            = 0x03D0D,
    MSG_GUILD_BANK_MONEY_WITHDRAWN                   = 0x00,
    MSG_GUILD_EVENT_LOG_QUERY                        = 0x00, /* old 0x05CA4 */
    CMSG_MAELSTROM_RENAME_GUILD                      = 0x00,
    CMSG_GET_MIRRORIMAGE_DATA                        = 0x00,
    SMSG_MIRRORIMAGE_DATA                            = 0x00,
    SMSG_FORCE_DISPLAY_UPDATE                        = 0x00,
    SMSG_SPELL_CHANCE_RESIST_PUSHBACK                = 0x00,
    CMSG_IGNORE_DIMINISHING_RETURNS_CHEAT            = 0x00,
    SMSG_IGNORE_DIMINISHING_RETURNS_CHEAT            = 0x00,
    CMSG_KEEP_ALIVE                                  = 0x10000, /* old 0x066A0 */
    SMSG_RAID_READY_CHECK_ERROR                      = 0x00,
    CMSG_OPT_OUT_OF_LOOT                             = 0x00,
    MSG_QUERY_GUILD_BANK_TEXT                        = 0x00,
    CMSG_SET_GUILD_BANK_TEXT                         = 0x00,
    CMSG_SET_GRANTABLE_LEVELS                        = 0x00,
    CMSG_GRANT_LEVEL                                 = 0x00,
    CMSG_REFER_A_FRIEND                              = 0x00,
    MSG_GM_CHANGE_ARENA_RATING                       = 0x00,
    CMSG_DECLINE_CHANNEL_INVITE                      = 0x00,
    SMSG_GROUPACTION_THROTTLED                       = 0x00,
    SMSG_OVERRIDE_LIGHT                              = 0x00,
    SMSG_TOTEM_CREATED                               = 0x00,
    CMSG_TOTEM_DESTROYED                             = 0x00, /* old 0x06680 */
    CMSG_EXPIRE_RAID_INSTANCE                        = 0x00,
    CMSG_NO_SPELL_VARIANCE                           = 0x00,
    CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY            = 0x00, /* old 0x01284 */
    SMSG_QUESTGIVER_STATUS_MULTIPLE                  = 0x00, /* old 0x00026 */
    CMSG_SET_PLAYER_DECLINED_NAMES                   = 0x00,
    SMSG_SET_PLAYER_DECLINED_NAMES_RESULT            = 0x00,
    CMSG_QUERY_SERVER_BUCK_DATA                      = 0x00,
    CMSG_CLEAR_SERVER_BUCK_DATA                      = 0x00,
    SMSG_SERVER_BUCK_DATA                            = 0x00,
    SMSG_SEND_UNLEARN_SPELLS                         = 0x045ED, /* old 0x048A0 */
    SMSG_PROPOSE_LEVEL_GRANT                         = 0x00,
    CMSG_ACCEPT_LEVEL_GRANT                          = 0x00,
    SMSG_REFER_A_FRIEND_FAILURE                      = 0x00,
    SMSG_SPLINE_MOVE_SET_FLYING                      = 0x00,
    SMSG_SPLINE_MOVE_UNSET_FLYING                    = 0x00,
    SMSG_SUMMON_CANCEL                               = 0x00,
    CMSG_CHANGE_PERSONAL_ARENA_RATING                = 0x00,
    CMSG_ALTER_APPEARANCE                            = 0x00,
    SMSG_ENABLE_BARBER_SHOP                          = 0x00,
    SMSG_BARBER_SHOP_RESULT                          = 0x00, /* old 0x01286 */
    CMSG_CALENDAR_GET_CALENDAR                       = 0x00, /* old 0x062A6 */
    CMSG_CALENDAR_GET_EVENT                          = 0x00, /* old 0x03022 */
    CMSG_CALENDAR_GUILD_FILTER                       = 0x00, /* old 0x02C04 */
    CMSG_CALENDAR_ARENA_TEAM                         = 0x00, /* old 0x00202 */
    CMSG_CALENDAR_ADD_EVENT                          = 0x00, /* old 0x02E84 */
    CMSG_CALENDAR_UPDATE_EVENT                       = 0x00, /* old 0x07206 */
    CMSG_CALENDAR_REMOVE_EVENT                       = 0x00, /* old 0x07482 */
    CMSG_CALENDAR_COPY_EVENT                         = 0x00, /* old 0x05604 */
    CMSG_CALENDAR_EVENT_INVITE                       = 0x00, /* old 0x04000 */
    CMSG_CALENDAR_EVENT_RSVP                         = 0x00, /* old 0x05000 */
    CMSG_CALENDAR_EVENT_REMOVE_INVITE                = 0x00, /* old 0x01602 */
    CMSG_CALENDAR_EVENT_STATUS                       = 0x00, /* old 0x07886 */
    CMSG_CALENDAR_EVENT_MODERATOR_STATUS             = 0x00, /* old 0x01002 */
    SMSG_CALENDAR_SEND_CALENDAR                      = 0x00, /* old 0x07E06 */
    SMSG_CALENDAR_SEND_EVENT                         = 0x00, /* old 0x03EA0 */
    SMSG_CALENDAR_FILTER_GUILD                       = 0x00, /* old 0x01CA0 */
    SMSG_CALENDAR_ARENA_TEAM                         = 0x00, /* old 0x07202 */
    SMSG_CALENDAR_EVENT_INVITE                       = 0x00, /* old 0x00E84 */
    SMSG_CALENDAR_EVENT_INVITE_REMOVED               = 0x00, /* old 0x04800 */
    SMSG_CALENDAR_EVENT_STATUS                       = 0x00, /* old 0x00A22 */
    SMSG_CALENDAR_COMMAND_RESULT                     = 0x00, /* old 0x06626 */
    SMSG_CALENDAR_RAID_LOCKOUT_ADDED                 = 0x00, /* old 0x05806 */
    SMSG_CALENDAR_RAID_LOCKOUT_REMOVED               = 0x00, /* old 0x020A6 */
    SMSG_CALENDAR_EVENT_INVITE_ALERT                 = 0x00, /* old 0x060A4 */
    SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT         = 0x00, /* old 0x014A2 */
    SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT          = 0x00, /* old 0x00082 */
    SMSG_CALENDAR_EVENT_REMOVED_ALERT                = 0x00, /* old 0x03E26 */
    SMSG_CALENDAR_EVENT_UPDATED_ALERT                = 0x00, /* old 0x01A04 */
    SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT       = 0x00, /* old 0x05424 */
    CMSG_CALENDAR_COMPLAIN                           = 0x00,
    CMSG_CALENDAR_GET_NUM_PENDING                    = 0x00, /* old 0x03422 */
    SMSG_CALENDAR_SEND_NUM_PENDING                   = 0x00, /* old 0x054A2 */
    CMSG_SAVE_DANCE                                  = 0x00,
    SMSG_NOTIFY_DANCE                                = 0x00, /* old 0x03204 */
    CMSG_PLAY_DANCE                                  = 0x00, /* old 0x018A2 */
    SMSG_PLAY_DANCE                                  = 0x00, /* old 0x010A0 */
    CMSG_LOAD_DANCES                                 = 0x00,
    CMSG_STOP_DANCE                                  = 0x00, /* old 0x00226 */
    SMSG_STOP_DANCE                                  = 0x00, /* old 0x04622 */
    CMSG_SYNC_DANCE                                  = 0x00,
    CMSG_DANCE_QUERY                                 = 0x00, /* old 0x05A02 */
    SMSG_DANCE_QUERY_RESPONSE                        = 0x00, /* old 0x02280 */
    SMSG_INVALIDATE_DANCE                            = 0x00, /* old 0x07A02 */
    CMSG_DELETE_DANCE                                = 0x00,
    SMSG_LEARNED_DANCE_MOVES                         = 0x04505, /* old 0x00886 */
    CMSG_LEARN_DANCE_MOVE                            = 0x00,
    CMSG_UNLEARN_DANCE_MOVE                          = 0x00,
    CMSG_SET_RUNE_COUNT                              = 0x00,
    CMSG_SET_RUNE_COOLDOWN                           = 0x00,
    MSG_MOVE_SET_PITCH_RATE_CHEAT                    = 0x00,
    MSG_MOVE_SET_PITCH_RATE                          = 0x00,
    SMSG_FORCE_PITCH_RATE_CHANGE                     = 0x00,
    CMSG_FORCE_PITCH_RATE_CHANGE_ACK                 = 0x00,
    SMSG_SPLINE_SET_PITCH_RATE                       = 0x00,
    SMSG_MOVE_ABANDON_TRANSPORT                      = 0x00,
    SMSG_CALENDAR_UPDATE_INVITE_LIST                 = 0x00,
    SMSG_CALENDAR_UPDATE_INVITE_LIST2                = 0x00,
    CMSG_UPDATE_MISSILE_TRAJECTORY                   = 0x00,
    SMSG_UPDATE_ACCOUNT_DATA_COMPLETE                = 0x00, /* old 0x040A5 */
    SMSG_TRIGGER_MOVIE                               = 0x00, /* old 0x03AA6 */
    CMSG_COMPLETE_MOVIE                              = 0x00, /* old 0x030A0 */
    CMSG_SET_GLYPH_SLOT                              = 0x00,
    CMSG_SET_GLYPH                                   = 0x00,
    SMSG_ACHIEVEMENT_EARNED                          = 0x00,
    SMSG_DYNAMIC_DROP_ROLL_RESULT                    = 0x00,
    SMSG_CRITERIA_UPDATE                             = 0x00, /* old 0x074A0 */
    CMSG_QUERY_INSPECT_ACHIEVEMENTS                  = 0x00, /* old 0x068A0 */
    SMSG_RESPOND_INSPECT_ACHIEVEMENTS                = 0x00, /* old 0x026AA */
    CMSG_DISMISS_CONTROLLED_VEHICLE                  = 0x00,
    CMSG_COMPLETE_ACHIEVEMENT_CHEAT                  = 0x00,
    SMSG_COMPRESSED_RESPOND_INSPECT_ACHIEVEMENTS     = 0x00,
    SMSG_COMPRESSED_ACHIEVEMENT_DATA                 = 0x00,
    SMSG_QUESTUPDATE_ADD_PVP_KILL                    = 0x00,
    CMSG_SET_CRITERIA_CHEAT                          = 0x00,
    SMSG_CALENDAR_UPDATE_INVITE_LIST3                = 0x00,
    CMSG_UNITANIMTIER_CHEAT                          = 0x00,
    CMSG_CHAR_CUSTOMIZE                              = 0x00,
    SMSG_CHAR_CUSTOMIZE                              = 0x00,
    SMSG_PET_RENAMEABLE                              = 0x00,
    CMSG_REQUEST_VEHICLE_EXIT                        = 0x00,
    CMSG_REQUEST_PLAYER_VEHICLE_EXIT                 = 0x00,
    CMSG_REQUEST_VEHICLE_PREV_SEAT                   = 0x00,
    CMSG_REQUEST_VEHICLE_NEXT_SEAT                   = 0x00,
    CMSG_REQUEST_VEHICLE_SWITCH_SEAT                 = 0x00,
    CMSG_PET_LEARN_TALENT                            = 0x00,
    CMSG_PET_UNLEARN_TALENTS                         = 0x00,
    SMSG_SET_PHASE_SHIFT                             = 0x01E21,
    SMSG_ALL_ACHIEVEMENT_DATA                        = 0x004E0,
    CMSG_FORCE_SAY_CHEAT                             = 0x00,
    SMSG_HEALTH_UPDATE                               = 0x00, /* old 0x03C02 */
    SMSG_POWER_UPDATE                                = 0x00, /* old 0x068A6 */
    CMSG_GAMEOBJ_REPORT_USE                          = 0x00,
    SMSG_HIGHEST_THREAT_UPDATE                       = 0x00, /* old 0x07480 */
    SMSG_THREAT_UPDATE                               = 0x00, /* old 0x00286 */
    SMSG_THREAT_REMOVE                               = 0x00, /* old 0x03886 */
    SMSG_THREAT_CLEAR                                = 0x06DA1,
    SMSG_CONVERT_RUNE                                = 0x00,
    SMSG_RESYNC_RUNES                                = 0x00,
    SMSG_ADD_RUNE_POWER                              = 0x00,
    CMSG_START_QUEST                                 = 0x00,
    CMSG_REMOVE_GLYPH                                = 0x00,
    CMSG_DUMP_OBJECTS                                = 0x00,
    SMSG_DUMP_OBJECTS_DATA                           = 0x00,
    CMSG_DISMISS_CRITTER                             = 0x00,
    SMSG_NOTIFY_DEST_LOC_SPELL_CAST                  = 0x00,
    CMSG_AUCTION_LIST_PENDING_SALES                  = 0x00,
    SMSG_AUCTION_LIST_PENDING_SALES                  = 0x06DCF,
    SMSG_MODIFY_COOLDOWN                             = 0x00,
    SMSG_PET_UPDATE_COMBO_POINTS                     = 0x00,
    CMSG_ENABLETAXI                                  = 0x00,
    SMSG_PRE_RESURRECT                               = 0x00, /* old 0x00E86 */
    SMSG_AURA_UPDATE_ALL                             = 0x00, /* old 0x05426 */
    SMSG_AURA_UPDATE                                 = 0x00, /* old 0x00C20 */
    CMSG_FLOOD_GRACE_CHEAT                           = 0x00,
    SMSG_SERVER_FIRST_ACHIEVEMENT                    = 0x00,
    SMSG_PET_LEARNED_SPELL                           = 0x00,
    SMSG_PET_REMOVED_SPELL                           = 0x00,
    CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE          = 0x00,
    CMSG_HEARTH_AND_RESURRECT                        = 0x00,
    SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA        = 0x02503, // ???
    SMSG_CRITERIA_DELETED                            = 0x00,
    SMSG_ACHIEVEMENT_DELETED                         = 0x00,
    CMSG_SERVER_INFO_QUERY                           = 0x00,
    SMSG_SERVER_INFO_RESPONSE                        = 0x01E00,
    CMSG_CHECK_LOGIN_CRITERIA                        = 0x00,
    SMSG_SERVER_BUCK_DATA_START                      = 0x00,
    CMSG_QUERY_VEHICLE_STATUS                        = 0x00,
    SMSG_BATTLEGROUND_INFO_THROTTLED                 = 0x00,
    SMSG_PLAYER_VEHICLE_DATA                         = 0x02503,
    CMSG_PLAYER_VEHICLE_ENTER                        = 0x00,
    CMSG_EJECT_PASSENGER                             = 0x00,
    SMSG_PET_GUIDS                                   = 0x00,
    SMSG_CLIENTCACHE_VERSION                         = 0x0453D, // 4.3.2 15211
    SMSG_ITEM_REFUND_INFO_RESPONSE                   = 0x00, /* old 0x066AE */
    CMSG_ITEM_REFUND_INFO                            = 0x00, /* old 0x06EA4 */
    CMSG_ITEM_REFUND                                 = 0x00, /* old 0x04EA2 */
    SMSG_ITEM_REFUND_RESULT                          = 0x00, /* old 0x02EAA */
    CMSG_CORPSE_MAP_POSITION_QUERY                   = 0x00, /* old 0x02E20 */
    SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE          = 0x00,
    CMSG_LFG_SET_ROLES_2                             = 0x00,
    CMSG_CALENDAR_CONTEXT_EVENT_SIGNUP               = 0x00,
    SMSG_CALENDAR_ACTION_PENDING                     = 0x00,
    SMSG_EQUIPMENT_SET_LIST                          = 0x00, /* old 0x05820 */
    CMSG_EQUIPMENT_SET_SAVE                          = 0x00, /* old 0x05C26 */
    CMSG_UPDATE_PROJECTILE_POSITION                  = 0x00,
    SMSG_SET_PROJECTILE_POSITION                     = 0x00,
    SMSG_TALENTS_INFO                                = 0x045B3,
    CMSG_LEARN_PREVIEW_TALENTS                       = 0x00,
    CMSG_LEARN_PREVIEW_TALENTS_PET                   = 0x00,
    SMSG_ARENA_OPPONENT_UPDATE                       = 0x00,
    SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED             = 0x00,
    SMSG_MULTIPLE_PACKETS                            = 0x00, /* old 0x07EA4 */
    SMSG_MOVE_GRAVITY_DISABLE                        = 0x00,
    CMSG_MOVE_GRAVITY_DISABLE_ACK                    = 0x00,
    SMSG_MOVE_GRAVITY_ENABLE                         = 0x00,
    CMSG_MOVE_GRAVITY_ENABLE_ACK                     = 0x00,
    SMSG_MOVE_LEVITATING                             = 0x00,
    SMSG_SPLINE_MOVE_GRAVITY_DISABLE                 = 0x00,
    SMSG_SPLINE_MOVE_GRAVITY_ENABLE                  = 0x00,
    CMSG_EQUIPMENT_SET_USE                           = 0x00, /* old 0x02226 */
    SMSG_EQUIPMENT_SET_USE_RESULT                    = 0x00,
    SMSG_UNKNOWN_1240                                = 0x00,
    CMSG_CHAR_FACTION_CHANGE                         = 0x00,
    SMSG_CHAR_FACTION_CHANGE                         = 0x00, /* old 0x002A5 */
    SMSG_BATTLEFIELD_MGR_ENTRY_INVITE                = 0x00, /* old 0x04CA8 */
    CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE       = 0x00,
    SMSG_BATTLEFIELD_MGR_ENTERED                     = 0x00,
    SMSG_BATTLEFIELD_MGR_QUEUE_INVITE                = 0x00, /* old 0x00608 */
    CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE       = 0x00,
    CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST               = 0x00,
    SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE      = 0x00, /* old 0x00C0E */
    SMSG_BATTLEFIELD_MGR_EJECT_PENDING               = 0x00, /* old 0x02EBE */
    SMSG_BATTLEFIELD_MGR_EJECTED                     = 0x00, /* old 0x02618 */
    CMSG_BATTLEFIELD_MGR_EXIT_REQUEST                = 0x00,
    SMSG_BATTLEFIELD_MGR_STATE_CHANGE                = 0x00,
    CMSG_WARGAME_ACCEPT                              = 0x00,
    CMSG_WARGAME_REQUEST                             = 0x00,
    SMSG_WARGAME_REQUEST_RESPONSE                    = 0x00,
    SMSG_WARGAME_REQUEST_SENT                        = 0x00,
    MSG_SET_RAID_DIFFICULTY                          = 0x00,
    SMSG_TOGGLE_XP_GAIN                              = 0x00450,
    SMSG_GMRESPONSE_DB_ERROR                         = 0x00,
    SMSG_GMRESPONSE_RECEIVED                         = 0x00,
    CMSG_GMRESPONSE_RESOLVE                          = 0x00,
    SMSG_GMRESPONSE_STATUS_UPDATE                    = 0x00,
    CMSG_WORLD_STATE_UI_TIMER_UPDATE                 = 0x00, /* old 0x00884 */
    SMSG_WORLD_STATE_UI_TIMER_UPDATE                 = 0x00, /* old 0x06222 */
    CMSG_CHAR_RACE_CHANGE                            = 0x00,
    SMSG_TALENTS_INVOLUNTARILY_RESET                 = 0x045B3,
    SMSG_LOOT_SLOT_CHANGED                           = 0x00,
    CMSG_READY_FOR_ACCOUNT_DATA_TIMES                = 0x0452B, // 4.3.2 15211
    CMSG_QUERY_QUESTS_COMPLETED                      = 0x00B20,
    SMSG_QUERY_QUESTS_COMPLETED_RESPONSE             = 0x014F5,
    CMSG_GM_REPORT_LAG                               = 0x00, /* old 0x06CA6 */
    SMSG_CORPSE_NOT_IN_INSTANCE                      = 0x00, /* old 0x03282 */
    CMSG_SET_ALLOW_LOW_LEVEL_RAID1                   = 0x00,
    CMSG_SET_ALLOW_LOW_LEVEL_RAID2                   = 0x00,
    SMSG_CAMERA_SHAKE                                = 0x00,
    SMSG_UPDATE_ITEM_ENCHANTMENTS                    = 0x00, /* old 0x078A4 */
    SMSG_REDIRECT_CLIENT                             = 0x01329, // 4.3.2 15211
    CMSG_REDIRECTION_FAILED                          = 0x00,
    SMSG_UNKNOWN_1295                                = 0x00309, // SMSG_SUSPEND_COMMS
    CMSG_UNKNOWN_1296                                = 0x00042, //  CMSG_SUSPEND_COMMS_ACK
    SMSG_FORCE_SEND_QUEUED_PACKETS                   = 0x00308,
    CMSG_REDIRECTION_AUTH_PROOF                      = 0x0004A, // 4.3.2 15211
    SMSG_COMBAT_LOG_MULTIPLE                         = 0x00,
    SMSG_LFG_OPEN_FROM_GOSSIP                        = 0x00,
    SMSG_UNKNOWN_1302                                = 0x00EE1,
    CMSG_UNKNOWN_1303                                = 0x00,
    SMSG_UNKNOWN_1304                                = 0x00,
    CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND          = 0x00,
    SMSG_UNKNOWN_1308                                = 0x00,
    CMSG_TRANSFORM                                   = 0x00,
    SMSG_UNKNOWN_1310                                = 0x00,
    SMSG_UNKNOWN_1311                                = 0x00,
    SMSG_UNKNOWN_1312                                = 0x00,
    SMSG_UNKNOWN_1314                                = 0x00,
    SMSG_UNKNOWN_1315                                = 0x00,
    SMSG_UNKNOWN_1316                                = 0x00,
    SMSG_UNKNOWN_1317                                = 0x00,
    CMSG_UNKNOWN_1320                                = 0x00,
    SMSG_UNKNOWN_1329                                = 0x00,
    SMSG_BATTLEGROUND_IN_PROGRESS                    = 0x00,
    SMSG_BATTLEGROUND_EXIT_QUEUE                     = 0x00,
    SMSG_BATTLEGROUND_WAIT_JOIN                      = 0x00,
    CMSG_BATTLEGROUND_PORT_AND_LEAVE                 = 0x00,
    SMSG_GUILD_XP_LIMIT                              = 0x00,
    CMSG_GUILD_QUERY_NEWS                            = 0x00,
    CMSG_GUILD_QUERY_XP                              = 0x00,
    SMSG_GUILD_XP                                    = 0x01C94,
    SMSG_GUILD_UPDATE_PARTY_STATE                    = 0x00,
    CMSG_GUILD_UPDATE_PARTY_STATE                    = 0x00,
    SMSG_SEND_QUEUED_PACKETS                         = 0x00,
    CMSG_REDIRECT_AUTH_PROOF                         = 0x00,
    CMSG_AUTO_DECLINE_GUILD_INVITES                  = 0x00,
    CMSG_SET_PRIMARY_TALENT_TREE                     = 0x00,
    CMSG_GROUP_SET_ROLES                             = 0x00,
    SMSG_UNKNOWN_65508                               = 0x00,
    SMSG_GUILD_ACHIEVEMENT_EARNED                    = 0x00,
    SMSG_GUILD_ACHIEVEMENT_DATA                      = 0x00,
    CMSG_UI_TIME_REQUEST                             = 0x00,
    SMSG_UI_TIME                                     = 0x00,
    CMSG_RETURN_TO_GRAVEYARD                         = 0x00, /* old 0x06603 */
    SMSG_UNKNOWN_1330                                = 0x00,
    CMSG_REFORGE_ITEM                                = 0x00,
    CMSG_COMPLETED_ARTIFACTS                         = 0x00,
    SMSG_COMPLETED_ARTIFACTS                         = 0x00, // structure: uint32 (count) loop: uint32(id), uint32(date), uint32(number of times completed) :endloop
    SMSG_ARTIFACT_COMPLETED                          = 0x00,
    CMSG_SET_FOCUSED_ACHIEVEMENT                     = 0x00,
    SMSG_REFORGE_OPEN_FROM_GOSSIP                    = 0x00,
    SMSG_UNKNOWN_GOLD                                = 0x00, // gives gold to the player
    SMSG_REQUEST_WAR_GAME_RESPONSE                   = 0x00,
    SMSG_SERVER_MESSAGE_BOX                          = 0x00, // Server msgbox-like
    SMSG_TALENT_ERROR                                = 0x00,
    SMSG_SEND_ERROR_MESSAGE                          = 0x00, // this has its own enum u8+u32+u32 special
    CMSG_GET_GUILD_ACHIEVEMENT_MEMBERS               = 0x00,
    SMSG_SEND_GUILD_ACHIEVEMENT_MEMBERS              = 0x00,
    CMSG_CLEAR_RAID_MARKER                           = 0x00,
    CMSG_REQUEST_GUILD_PARTY_STATE                   = 0x001E0,
    CMSG_GET_GUILD_MEMBER_RECIPES                    = 0x01470,
    CMSG_QUERY_GUILD_MEMBERS_FOR_RECIPE              = 0x00,
    CMSG_GUILD_NEWS_SET_STICKY                       = 0x00,
    CMSG_LOG_DISCONNECT                              = 0x04019, // 4.3.2 15211
    CMSG_VIOLENCE_LEVEL                              = 0x02B85, /* old 0x07291 */
    //SMSG_CUF_PROFILES_LOAD                           = 0x01494,
    SMSG_PLAYER_MOVE                                 = 0x01425,
    CMSG_REQUEST_CEMETERY_LIST                       = 0x003A4, /* old 0x02081 */
    SMSG_REQUEST_CEMETERY_LIST_RESPONSE              = 0x00405,
    CMSG_RANDOMIZE_CHAR_NAME                         = 0x00, /* old 0x04326 */
    SMSG_RANDOMIZE_CHAR_NAME                         = 0x00, /* old 0x024BA */
    CMSG_TRANSMOGRIFY_ITEMS                          = 0x00, /* old 0x03081 */
    SMSG_ITEM_EXPIRE_PURCHASE_REFUND                 = 0x00, /* old 0x02C08 */
    SMSG_ITEM_QUERY_SINGLE_RESPONSE                  = 0x00, /* old 0x06E8C */
    CMSG_UNLOCK_VOID_STORAGE                         = 0x00, /* old 0x02681 */
    CMSG_VOID_STORAGE_TRANSFER                       = 0x00, /* old 0x02011 */
    SMSG_VOID_ITEM_SWAP_RESPONSE                     = 0x00, /* old 0x00C1C */
    SMSG_VOID_STORAGE_CONTENTS                       = 0x00, /* old 0x00A8A */
    SMSG_VOID_STORAGE_FAILED                         = 0x00, /* old 0x0263C */
    SMSG_VOID_STORAGE_TRANSFER_CHANGES               = 0x00, /* old 0x04CAE */
    SMSG_VOID_TRANSFER_RESULT                        = 0x00, /* old 0x02CA8 */
    CMSG_QUERY_VOID_STORAGE                          = 0x00, /* old 0x03431 */
    CMSG_SWAP_VOID_ITEM                              = 0x00, /* old 0x03291 */
    CMSG_OBJECT_UPDATE_FAILURE                       = 0x00, /* old 0x07233 */
    SMSG_VERIFY_CONNECTIVITY                         = 0x00, /* old 0x04F57 */
    CMSG_VERIFY_CONNECTIVITY_RESPONSE                = 0x10002 /* old 0x04C52 */
};

extern void InitOpcodeTable();

///- Player state
enum SessionStatus
{
    STATUS_AUTHED = 0,                                      // Player authenticated (_player == NULL, m_playerRecentlyLogout = false or will be reset before handler call, m_GUID have garbage)
    STATUS_LOGGEDIN,                                        // Player in game (_player != NULL, m_GUID == _player->GetGUID(), inWorld())
    STATUS_TRANSFER,                                        // Player transferring to another map (_player != NULL, m_GUID == _player->GetGUID(), !inWorld())
    STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT,                    // _player!= NULL or _player == NULL && m_playerRecentlyLogout, m_GUID store last _player guid)
    STATUS_NEVER,                                           // Opcode not accepted from client (deprecated or server side only)
    STATUS_UNHANDLED                                        // Opcode not handled yet
};

enum PacketProcessing
{
    PROCESS_INPLACE = 0,                                    //process packet whenever we receive it - mostly for non-handled or non-implemented packets
    PROCESS_THREADUNSAFE,                                   //packet is not thread-safe - process it in World::UpdateSessions()
    PROCESS_THREADSAFE                                      //packet is thread-safe - process it in Map::Update()
};

class WorldPacket;

typedef void(WorldSession::*pOpcodeHandler)(WorldPacket& recvPacket);

struct OpcodeHandler
{
    OpcodeHandler() {}
    OpcodeHandler(const char* _name, SessionStatus _status, PacketProcessing _processing, pOpcodeHandler _handler)
        : name(_name), status(_status), packetProcessing(_processing), handler(_handler) {}

    char const* name;
    SessionStatus status;
    PacketProcessing packetProcessing;
    pOpcodeHandler handler;
};

extern OpcodeHandler* opcodeTable[NUM_OPCODE_HANDLERS];
void InitOpcodes();

/// Lookup opcode name for human understandable logging
inline const char* LookupOpcodeName(Opcodes id)
{
    if (id < NUM_OPCODE_HANDLERS)
    {
        OpcodeHandler* handler = opcodeTable[uint32(id)];
        return handler ? handler->name : "UNKNOWN OPCODE";
    }
    else
        return "UNKNOWN OPCODE";
}
#endif
/// @}
